### ISSUE TITLE
A way to test workbox locally

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/pwa-module#11]
Is there any guidelines how to run workbox in dev mode?

**Comment by pi0** [comment]
Hi. This is now possible to enable debug mode by setting `workbox.debug: true`. But unfortunately this is not possible adding to `nuxt dev` as Webpack uses an in-memory file system and it needs some changes in Workbox package itself ... I'll close this issue as there is not anything planned but PRs welcome :)

**Comment by renatodex** [comment]
Hi @pi0 ,
Could you be more specific on the technical limitations on this? 
If i had the right direction, i could start working in a temporary solution.
