### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by matamune94** [nuxt-community/pwa-module#120]
i make this warning when install pwa , how can fix it ?

**Comment by manniL** [comment]
@matamune94 Will be fixed with the next release

**Comment by MarvinMiles** [comment]
Still have this warning (v2.6.0) :(

**Comment by manniL** [comment]
@MarvinMiles There wasn't a major release yet. see #103

**Comment by manniL** [comment]
See comment from https://github.com/nuxt/create-nuxt-app/issues/185#issuecomment-466757262

**Comment by tomshaw** [comment]
I just created my first Nuxt app and getting this error. Reluctant to try of the beta until it's finalized.

**Comment by imShara** [comment]
v2.7.1 Still here

**Comment by mauxtin** [comment]
@imShara Feel free to update to the latest beta (v3.0.0-beta.16).
