### ISSUE TITLE
Icons arent passed to manifest

### ISSUE THREAD

**Issue by Biskor** [nuxt-community/pwa-module#128]
Hello,

Im facing an issue,

Icon module generate icons for PWA. but they're never passed to options.manifest because Icons, Meta and Workbox module are called in a build before hook (build:before), manifest module didnt have this function implemented and is called before all....

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c90">#c90</a>)</em></sub></div>

**Comment by Biskor** [comment]
Ok, this is updated in the last version.

**Comment by pi0** [comment]
@Biskor feel free reopening issue if still having problems.
