### ISSUE TITLE
Disable not override some default meta?

### ISSUE THREAD

**Issue by tsimenis** [nuxt-community/pwa-module#13]
Hi there, 

so I am using the module, mainly for the icon. 
Regarding the meta, I am getting the meta I need from my endpoints in my application and I set them in head. 

I want to disable some of the meta that the module applies and not override them.
Specifically the `og:type` `og:title` `og:description`, the module inserts them as meta name, while they should be meta property. 

Here is the output on my page

![meta-output](https://user-images.githubusercontent.com/5978397/32906948-c5800c1e-cafe-11e7-8618-85a4e6d993e1.png)

And this is my nuxt config

![nuxtconfig](https://user-images.githubusercontent.com/5978397/32907000-ece77a9e-cafe-11e7-82f0-3806138f956a.png)

**Comment by pi0** [comment]
Hi. This will be fixed in next release, for now you can disable all og related meta props using this nuxt.config.js:

```js
meta: {
 ogType: false,
 ogTitle: false,
 ogDescription: false
}
```

**Comment by tsimenis** [comment]
Just to be totally sure, the meta should be outside of the head in nuxt.config.js, 
so something like this?

![nuxtconfig](https://user-images.githubusercontent.com/5978397/32907660-0eb53aec-cb01-11e7-8f41-51b93d8a1a4f.png)

**Comment by pi0** [comment]
This should be fine if using [meta@1.5.3](https://unpkg.com/@nuxtjs/meta@1.5.3/index.js). If not working i suggest await for 2.0.0 release (ETA approx tonight)

**Comment by tsimenis** [comment]
Great yes that's the version I'm using, it works!

So after the new release will I need to change it?

thanks :)

**Comment by pi0** [comment]
Your welcome. Nope. I've added checks for `property` attribute in custom meta to prevent overriding. Also, it should make correct og tags by default if not explicitly disabled.
