### ISSUE TITLE
OneSignal integration discussion

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/pwa-module#16]
Thanks for the new module. I have a few suggestions regarding subject:

- add ```trace``` or ```level``` option to set up log level in config depending on env:
```js
if (process.env.NODE_ENV === 'development') {
  OneSignal.push(() => OneSignal.log.setLevel('trace'))
}
```
- add condition or callback whether to init module, e.g. only for authenticated users
- if some options need to be translated (like ```welcomeNotification``` or ```promptOptions```) how to do this in nuxt config?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c14">#c14</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @Darkside73. Nice suggestions. I'll dig into when had free time. BTW PRs always welcome :)

**Comment by Darkside73** [comment]
Can you guide me for template syntax and how to test local version (simply add path in package.json or need to link it)?

**Comment by noobling** [comment]
I would love more information on this topic :)
