### ISSUE TITLE
OneSignal loaded twice in built SPA

### ISSUE THREAD

**Issue by motia** [nuxt-community/pwa-module#161]
### Version

[v3.0.0-beta.12](https://github.com/pwa-module/releases/tag/v3.0.0-beta.12)

### Reproduction link

[https://github.com/motia/nuxt-onesignal-fresh](https://github.com/motia/nuxt-onesignal-fresh)

### Steps to reproduce

```
git clone https://github.com/motia/nuxt-onesignal-fresh.git
yarn
yarn nuxt build
```
The SPA must be served on the domain `other.test`, otherwise you must change use your key.

### What is expected ?

The script is loaded once form built SPA.

### What is actually happening?

![onesignal-twice.PNG](https://cmty.s3.eu-west-1.amazonaws.com/105824549/a91f1320-413c-11e9-8097-eb8ace9f5b68.PNG)

### Additional comments?

This bug should not be problematic, because the script is loaded from a cdn with long cache.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c106">#c106</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi  and thanks for the report. This is normal that two onesignal related js files added (one is for update checks) but they should not be identical like the image above.

![image](https://user-images.githubusercontent.com/5158436/54496828-e7db8480-4908-11e9-8d8a-8b9857c5343c.png)

I've added a fix to ensure this behavior. Please check it on latest version and ping me if problem still happens.

**Comment by 8ctopotamus** [comment]
I have this issue too. Do I just reinstall the Nuxt PWA module in order to fix this?

**Comment by motia** [comment]
yes. the problem persists.

**Comment by burn4live** [comment]
still the same problem

**Comment by burn4live** [comment]
i have the same problem
