### ISSUE TITLE
ServiceWorker is in redundant state (sentry error)

### ISSUE THREAD

**Issue by joergac** [nuxt-community/pwa-module#166]
### Version

[v3.0.0-beta.12](https://github.com/pwa-module/releases/tag/v3.0.0-beta.12)

### Reproduction link

[https://codesandbox.io/s/ll0q81zjpz](https://codesandbox.io/s/ll0q81zjpz)

### Steps to reproduce

I am not sure how to reproduce it since it did not happen to me (I saw it on sentry).

I created a repository showing how I am using the module but I am not sure how to actually reproduce the error.

### What is expected ?

No error

### What is actually happening?

```
InvalidStateError: Failed to execute 'postMessage' on 'ServiceWorker': ServiceWorker is in redundant state.
  at Xe.i(./node_modules/workbox-window/build/workbox-window.prod.mjs:1:105)
  at new Promise(<anonymous>)
  at workbox_window_prod_t(./node_modules/workbox-window/build/workbox-window.prod.mjs:1:56)
  at R(./node_modules/workbox-window/build/workbox-window.prod.mjs:1:2208)
  at nt.register(./node_modules/workbox-window/build/workbox-window.prod.mjs:1:911)
  at ? (<anonymous>)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c109">#c109</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Error handling should be improved with latest version and hopefully no sentry logs like this anymore :)

**Comment by joergac** [comment]
Hey @pi0,

I am still getting a similar error in my dashboard.

Here is the full log
```
InvalidStateError: Failed to execute 'postMessage' on 'ServiceWorker': ServiceWorker is in redundant state.
  at ? (./node_modules/workbox-cdn/workbox/workbox-window.prod.es5.mjs:1:172)
  at new Promise(<anonymous>)
  at n(./node_modules/workbox-cdn/workbox/workbox-window.prod.es5.mjs:1:69)
  at j(./node_modules/workbox-cdn/workbox/workbox-window.prod.es5.mjs:1:2854)
  at ? (./node_modules/workbox-cdn/workbox/workbox-window.prod.es5.mjs:1:1567)
  at ? (<anonymous>)
```

**Comment by pi0** [comment]
@joergac Can you please share OS and Browser name/versions? This error is related to [workbox](https://github.com/GoogleChrome/workbox) but if having more details for reproduction we can report them to fix :)

**Comment by gpressutto5** [comment]
@pi0 Got the same error here using `v3.0.0-beta.16`:

**Browser**: Mobile Safari 12.1.1
**OS**: iOS 12.3.1
https://sentry.io/share/issue/1d4eb7158a3b4a959f1603dfb71f70af/

**Comment by pi0** [comment]
@gpressutto5 Would you please open an issue in [workbox](https://github.com/GoogleChrome/workbox) repo?

**Comment by gpressutto5** [comment]
@pi0 I have been using `@nuxtjs/pwa v2.6.0` for some time and this error never happened until I upgrade to `v3.0.0-beta.16`. Since `v2.6.0` used workbox too I don't think the problem is being caused by it. Were there any changes in workbox between these releases?

**Comment by pi0** [comment]
@gpressutto5 pwa module 2.x to 3.x also bumped workbox from 3.x to 4.x which is almost a huge rewrite.

**Comment by yanxlg** [comment]
So,what's the result of this issues?I meet it too,how can I to solve it?
