### ISSUE TITLE
Cannot read property 'controller' of undefined

### ISSUE THREAD

**Issue by joergac** [nuxt-community/pwa-module#167]
### Version

[v3.0.0-beta.13](https://github.com/pwa-module/releases/tag/v3.0.0-beta.13)

### Reproduction link

[https://codesandbox.io/s/ll0q81zjpz](https://codesandbox.io/s/ll0q81zjpz)

### Steps to reproduce

I got this error from sentry.

### What is expected ?

No errors.

### What is actually happening?

```
TypeError: Cannot read property 'controller' of undefined
  at handler(./node_modules/workbox-cdn/workbox/workbox-window.prod.es5.mjs:1:1482)
  at run(./node_modules/core-js/modules/es6.promise.js:75:1)
  at fn(./node_modules/core-js/modules/es6.promise.js:92:1)
  at MutationObserver.n(./node_modules/core-js/modules/_microtask.js:18:1)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c110">#c110</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This error is probably happening from users of prior to beta.13 in sentry logs. old (and almost majority of) iOS devices do not support service worker and `workbox-window` does not handle this. So this is generally a safe error to ignore. I'm working on better handling for the next beta.
