### ISSUE TITLE
This is a bug or my configuration problem ?

### ISSUE THREAD

**Issue by zhuweiyou** [nuxt-community/pwa-module#17]
![image](https://user-images.githubusercontent.com/8413791/33521818-b4379d7a-d817-11e7-8f00-ba55893affe4.png)

```js
modules: [
    ['@nuxtjs/pwa', {icon: false}],
],
manifest: {
    name: 'myname',
    short_name: 'myname',
    start_url: '/',
    theme_color: '#ffffff',
    background_color: '#505050'
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c9">#c9</a>)</em></sub></div>

**Comment by galvez** [comment]
@zhuweiyou `manifest` should go inside the configuration object after `@nuxtjs/pwa`

**Comment by manniL** [comment]
@galvez Doesn't have to. See this [example](https://github.com/Developmint/developmint.de/blob/master/nuxt.config.js#L223).

**Comment by galvez** [comment]
@manniL oh, gotcha. My bad.

**Comment by ninest** [comment]
Could this be related to #176?
