### ISSUE TITLE
corejs issues

### ISSUE THREAD

**Issue by dasZGFz** [nuxt-community/pwa-module#170]
### Version

[v3.0.0-beta.14](https://github.com/pwa-module/releases/tag/v3.0.0-beta.14)

### Reproduction link

[https://github.com/dasZGFz/das.zgfz.me](https://github.com/dasZGFz/das.zgfz.me)

### Steps to reproduce

Running the build displays all kinds of issues with core-js. Note: this repo is on nuxt-edge

### What is expected ?

The build should run.

### What is actually happening?

The build fails.

### Additional comments?

I narrowed this down to the pwa module by running `yarn remove @nuxtjs/pwa` and removing it from my nuxt config.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c112">#c112</a>)</em></sub></div>

**Comment by dasZGFz** [comment]
@pi0 Pinging you since you seem to be the main dev for this.

**Comment by pi0** [comment]
Thanks for report @dasZGFz. This is a nuxt issue because 2.6.5 is in `node_modules/core-js` and `3.0.0` is in `node_modules/@nuxt/babel-preset-app-[edge]/node_modules`. Working on it :)

**Comment by pi0** [comment]
fixed with 3.0.0-25886174.42eefa0e

**Comment by dasZGFz** [comment]
Great thanks!
