### ISSUE TITLE
Icon resize task blocks the main thread during build

### ISSUE THREAD

**Issue by jhnns** [nuxt-community/pwa-module#171]
### Version

[2.6.0](https://github.com/pwa-module/releases/tag/2.6.0)

### Reproduction link

[https://github.com/jhnns/nuxt-pwa-build-perf-demo](https://github.com/jhnns/nuxt-pwa-build-perf-demo)

### Steps to reproduce

- Create an initial nuxt project with `create-nuxt-app` and select the PWA module
- Run `node --inspect-brk ./node_modules/.bin/nuxt`
- Open Chrome and go to chrome://inspect/#devices
- Select Node process and create a profile

### What is expected ?

The icon resize task should start as soon as possible in a different process/thread to speed up the build.

### What is actually happening?

Here is a flamegraph that demonstrates that the icon resize task takes up more than half of the build time. But the bigger problem is that the task blocks the main thread which means that webpack can't start to do its work in the mean time. Here I've marked the resize task with red:
![Bildschirmfoto 2019-03-30 um 17.57.58 Kopie.jpg](https://cmty.s3.eu-west-1.amazonaws.com/105824549/e6f336d0-530d-11e9-8ac3-bba2794fcb4c.jpg)

You can see that webpack starts its work only after around 16s.

### Additional comments?

Spinning up a separate process doesn't come for free. Usually it's better to have a separate thread for this kind of task. We could do this with Node.js worker threads (https://nodejs.org/api/worker_threads.html) which are only available for Node >10.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c116">#c116</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @jhnns. Thanks for reporting this issue. Actually, this problem was not visible because normally the original icon is small-sized enough.

I've tried to make the issue more visible by using a bigger icon in the test fixture:

![image](https://user-images.githubusercontent.com/5158436/56980789-8ad31f80-6b92-11e9-8121-e71e86147b90.png)

I'm working on an icon module rewrite in a way that resize microtasks running in the background. (Initial read may be still required before build to generate hash and required meta)

**Comment by pi0** [comment]
Implemented in a4a457efe98461cf28249742952ca49e9ebfe847 (with some enhancenments including cache in later commits) I used normal `cp.fork` to support node <10.

![image](https://user-images.githubusercontent.com/5158436/56990974-c8907200-6bab-11e9-9523-04e1e0dd4d6a.png)

**Comment by jhnns** [comment]
> this problem was not visible because normally the original icon is small-sized

I never changed the icon. I just used the default icon (see also [reproduction link](https://github.com/jhnns/nuxt-pwa-build-perf-demo)).

> Implemented in a4a457e (with some enhancenments including cache in later commits) I used normal cp.fork to support node <10.

Awesome, the flame graph looks good 👍. I just left some comments at the commit :)

**Comment by pi0** [comment]
Thanks, @jhnns for the comments.

**Comment by pi0** [comment]
Released in [3.0.0-beta.15](https://github.com/nuxt-community/pwa-module/releases/tag/v3.0.0-beta.15)
