### ISSUE TITLE
Images not showing at all

### ISSUE THREAD

**Issue by mauxtin** [nuxt-community/pwa-module#175]
### Version

[v3.0.0-beta.14](https://github.com/pwa-module/releases/tag/v3.0.0-beta.14)

### Reproduction link

[http://noreproduction.com](http://noreproduction.com)

### Steps to reproduce

I am having a weird issue with my nuxt app and I think this is due to the pwa module.

Sometimes when I open my page the images are not showing up. If I then refresh the page the images are shown correctly. It's a bit weird so I am thinking that it has to be something with the caching. Could this be something the pwa module is responsible for? Or is it completely unrelated?

I am not even sure how to debug this..

### What is expected ?

Images to be shown

### What is actually happening?

Not showing

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c124">#c124</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Without reproduction (at least a running webpage to debug -- with name/version of the browser) we can't really help. PWA module uses [workbox](https://github.com/GoogleChrome/workbox) by Google for service worker.

**Comment by mauxtin** [comment]
@pi0 Can I just send you the website link on discord (or email or whatever) instead of here? :)

**Comment by pi0** [comment]
@mauxtin Sure. I'm @pi0#6582  on discord.

**Comment by mauxtin** [comment]
I am suspecting that this occurs due to caching when I push a new update. 

Could this be that the module fails to load the new js + css files whenever they change?

I am currently using the default filenames that Nuxt provide. I will try to update to `[name].js?id=[hash]` to test this out. If I am right, it should fix it.

Can you think of something @pi0? Can this be the case?

**Comment by pi0** [comment]
`[name].js?id=[hash]` even if works is not a solution. It can lead to loading incompatible chunks with same name.

**Comment by mauxtin** [comment]
You are right.. I am not sure what else I can do about that.

Maybe changing the strategy from `cacheFirst` to `networkFirst`?

(https://pwa.nuxtjs.org/modules/workbox.html#adding-custom-runtimecaching-items-for-cdn)

**Comment by pi0** [comment]
@mauxtin Are you using external CDN domain? If so probably yes. Even `staleWhileRevalidate` would be better.

**Comment by mauxtin** [comment]
The domain is on Cloudflare however I have cache disabled on it. 

The documentation is a bit vague though, would something like this work? Haven't used workbox before so I'd love your guidance on this.

```
  runtimeCaching: [
    {
      urlPattern: '.*',
      handler: 'staleWhileRevalidate',
      method: 'GET'
    }
  ]
```

**Comment by pi0** [comment]
If it is problematic you can disable default runtime caching by `offline: false`.

**Comment by mauxtin** [comment]
Tried `offline: false` without luck.

It's very strange because instead of the image I am getting this
```
<img src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%221%22%20height%3D%221%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20%25%7Bw%7D%20%25%7Bh%7D%22%20preserveAspectRatio%3D%22none%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20style%3D%22fill%3A%23fafafa%3B%22%3E%3C%2Frect%3E%3C%2Fsvg%3E" alt="Technology" width="1" height="1" class="position-absolute img-fluid" data-v-29acb58a="">
```
This happens only for the first page load each day. If I just refresh the page everything is back to normal.
```
<img src="https://s3-eu-west-1.amazonaws.com/xxxxxxxx/laptop.png" alt="Technology" class="position-absolute img-fluid" data-v-29acb58a="">
```

I am thinking that this might me a combination of `pwa-module` and `bootstrap-vue` lazy loading images.

Any ideas?

**Comment by pi0** [comment]
@mauxtin Yes could be possible as the prefilled SVG is from BV. Will try to propose a reprocution.
