### ISSUE TITLE
Restrict the pages that the "Add to Home Screen" dialog is showing

### ISSUE THREAD

**Issue by mauxtin** [nuxt-community/pwa-module#177]
### What problem does this feature solve?

I'd like to display the dialog only in homepage. I believe this is good UX for the user.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c127">#c127</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. You can use `beforeinstallprompt` event to listen and conditionally prevent displaying that banner:

`plugins/pwa.client.js`

```js
window.addEventListener('beforeinstallprompt', function (e) {
  // Prevent Chrome 67 and earlier from automatically showing the prompt
  e.preventDefault()
});
```

Source: https://love2dev.com/blog/beforeinstallprompt/

**Comment by filrak** [comment]
If you'd like to have it in a config anyway @pi0 I can take care of it. I was thinking about contributions to this module for some time and this simple task seems like a right choice to start

**Comment by pi0** [comment]
@filark Its Awesome about your will to contribute 😍 And always welcome.

For this case i think it needs manual impalement for each project (Like checking router, ..) so maybe it would be better to mention in the docs.

**Comment by filrak** [comment]
You mean there are some technical limitations for nuxt modules (like the are registered after the event is fired or no access to window object - I havn;t got a chance to write one yet so this questions may be dumb) or purely from UX perspective?

If it's from UX perspective I guess it might be a good addition if the module aims to provide everything out of the box and can be just a list of route strings. It will also make it easier to have all PWA-related features in one place. 

i'm not that familiar with vision of the project yet so if it just don't fit into this just close the issue ;)

**Comment by pi0** [comment]
@filrak Providing the ability to disable add to home screen in some conditions is reasonable also not a technical limitation. The module (workbox) provides a plugin to register `workbox-cdn`.  It is happening early enough to prevent install banner.

The question is what is the _condition_ to hide it or not. We can start with simple conditions like doing this against a simple route. Someone may want to also disable it for users with specific OS version or browser and so on...

I did not have positive feedback of adding such features in other nuxt modules. Users will usually feel limited by just an option. So this is why I think good documentation for ATH preventing would fit better here. (At least docs is more priority). If you have a different vision that a simple config can cover most of the users we can have both.

**Comment by filrak** [comment]
Ok, you're right. Your reasoning makes perfect sense - let's focus on docs then. It's not that common use case anyway and as you pointed out requires a lot of config options to be a complete solution ;)

**Comment by mauxtin** [comment]
Closing as @pi0 answer did the trick 🎉
