### ISSUE TITLE
manifest cross-origin issues

### ISSUE THREAD

**Issue by simllll** [nuxt-community/pwa-module#18]
Hi all,
I ran into some troubles with the manifest json since I changed the publicPath to a cdn.
If i run lighthouse it complains about same-origin policy for the manifest file. Even though I found https://github.com/w3c/manifest/issues/360 and it tunrs out cross origin should work just fine, the browser and several testing scenarios complain about it if the manifest is delivered by a different host.

I think it would be a easy fix if I can overwrite the publicPath within manifest module (I did the same for workbox ;), unfortantuly as I checked the source code of the manifest module I couldn't figure it out how to apply a different publicPath in this case. 

Would be great to add an option to overwrite the public path, If you want me to I can create a PR and try to fix it up? 

Thanks
Simon

**Lighthouse report - 1 failed Audit:**
User can be prompted to Install the Web App
Browsers can proactively prompt users to add your app to their homescreen, which can lead to higher engagement. Learn more.
Warnings: ERROR: start_url must be same-origin as document

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c11">#c11</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. I just didn't get the point but PRs welcome (And it would be 2x awesome if you can add some small docs about CDN usage). Thanks :)
