### ISSUE TITLE
Error: Cannot find module 'jimp'

### ISSUE THREAD

**Issue by fmoessle** [nuxt-community/pwa-module#182]
![image](https://user-images.githubusercontent.com/17830282/56854339-18b1cf00-6935-11e9-8b4e-786672904315.png)

See: [https://github.com/oliver-moran/jimp/issues/726](https://github.com/oliver-moran/jimp/issues/726)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c132">#c132</a>)</em></sub></div>

**Comment by pi0** [comment]
Closing as the original issue seems resolved.
