### ISSUE TITLE
PWA doesn't work with data I get from request in SPA mode

### ISSUE THREAD

**Issue by siberiadev** [nuxt-community/pwa-module#188]
I don't know is it normal behavior of pwa module that it doesn't work in spa mode with data I get from axios request?
Same time other static feature and functions work fine in PWA without wifi.
But when I try to open page with data from axios without wifi it gives me an error.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c134">#c134</a>)</em></sub></div>

**Comment by pi0** [comment]
@siberiadev Please elaborate more. What is the error? Also can you please share version of pwa and nuxt.config?

**Comment by Atinux** [comment]
Closing for non activity, you we enable stale bot @pi0 ?
