### ISSUE TITLE
Add to home screen is disable when add importScripts : nuxt.config.js

### ISSUE THREAD

**Issue by MaximeScibetta** [nuxt-community/pwa-module#196]
### Version

[v3.0.0-beta.16](https://github.com/pwa-module/releases/tag/v3.0.0-beta.16)

### Reproduction link

[https://webapp.letsgocity.be/](https://webapp.letsgocity.be/)

### Steps to reproduce

When I add the following code in my nuxt.config.js file

`workbox:{ importScripts: ['firebase-messaging-sw.js'] }`

The " Add to home screen " dialog isn't showing in my PWA, when I delete this line all work fine...

Anyone have solution ?

### What is expected ?

The " Add to home screen " dialog isn't showing in my PWA, when I delete this line all work fine..

### What is actually happening?

When I add the following code in my nuxt.config.js file

`workbox:{ importScripts: ['firebase-messaging-sw.js'] }`

The " Add to home screen " dialog isn't showing in my PWA, when I delete this line all work fine...

Anyone have solution ?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c145">#c145</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. In your reproduce seems firebase is not included. Can you please enable it and check console for any errors?

**Comment by MaximeScibetta** [comment]
This I nuxt.config.js
```
export default {
  mode: 'spa',

  /*
  ** Headers of the page
  */
  head: {
    title: "mobilO !",
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no', },
      { hid: 'description', name: 'description', content: "Application d'appelle de la navette Val-Benoît." }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  manifest: {
    name: 'mobilO !',
    short_name: 'mobilO',
    lang: 'fr',
    gcm_sender_id: "103953800507"
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },

  /*
  ** Global CSS
  */
  css: [
    // un fichier SCSS dans le projet
    '@/sass/styles.scss'
  ],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    "~/plugins/moment.js",
    "~/plugins/vue-touch.js"
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    'nuxt-material-design-icons',
    'vue-sweetalert2/nuxt',
    'cookie-universal-nuxt'
  ],
  workbox:{ 
    importScripts: ['firebase-messaging-sw.js']
  },
  /*
  ** Axios module configuration
  */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },

  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
    }
  },
  env: {
    auth: {
      clientId: 'lgc-admin-html',
      clientSecret: '77E3D87654B12EDC46CB4B918885B'
    }
  }
}
```
my `firebase-messaging-sw.js`
```
importScripts("https://www.gstatic.com/firebasejs/5.9.4/firebase-app.js");
importScripts("https://www.gstatic.com/firebasejs/5.9.4/firebase-messaging.js");

firebase.initializeApp({
// Project Settings => Add Firebase to your web app
  messagingSenderId: "341751669051"
});

if (firebase.messaging.isSupported()) {
  const messaging = firebase.messaging()
  messaging.setBackgroundMessageHandler(function(payload) {
    const promiseChain = clients
      .matchAll({
        type: "window",
        includeUncontrolled: true
      })
      .then(windowClients => {
        for (let i = 0; i < windowClients.length; i++) {
          const windowClient = windowClients[i];
          windowClient.postMessage(payload);
        }
      })
      .then(() => {
        console.log('We are not on app background', payload)
        return registration.showNotification(payload.notification.title)
      });
    return promiseChain;
  });
}

self.addEventListener('notificationclick', function(event) {

});
```
And with this settings I have push but no "Add to home screen" dialog and if I delete the line with `importScripts` I have "Add to home screen" dialog but no push notification

**Comment by MaximeScibetta** [comment]
> Hi. In your reproduce seems firebase is not included. Can you please enable it and check console for any errors?

@pi0  You have any suggest ?

**Comment by pi0** [comment]
I would be happy to help, however current version has this error:

![image](https://user-images.githubusercontent.com/5158436/60037692-7fe6c800-96c7-11e9-87b9-190e34ffe01c.png)

Also not reproducible as production [sw.js](https://webapp.letsgocity.be/sw.js) seems not containing firebase so can't guess what's wrong.

**Comment by MaximeScibetta** [comment]
@pi0 I have not an error of this type. My project works fine I just not have dialog for add to Home screen when I import my firebase-messaging-sw.js

**Comment by pi0** [comment]
Getting this error while opening URL: https://webapp.letsgocity.be

Also sw.js:

![image](https://user-images.githubusercontent.com/5158436/60038519-d6550600-96c9-11e9-98a9-c46894afcbad.png)

**Comment by MaximeScibetta** [comment]
It's database error is fixed now. 

And I've re deploy with my firebase sw

**Comment by pi0** [comment]
Strange indeed. We can try OneSignal workaround maybe it works. First, add these options:

```js
{
  workbox: {
    swURL: 'firebase-messaging-sw.js'
  }
}
```

And on top of `firebase-messaging-sw.js` file, add `importScripts('sw.js')`

**Comment by MaximeScibetta** [comment]
Yeaaah I think all works fine ! I'm comeback to you tomorrow after more testing if it's not fixed but I think it's ok. 

( other question :p ) It's possible to have multiple manifest.json

one for webapp.lgc.com/{uid}
an other for  webapp.lgc.com/{otherUid}
etc ... etc...

**Comment by pi0** [comment]
I'm not sure supporting multiple manifest is supported by spec. What would be the use case?

**Comment by MaximeScibetta** [comment]
A page connected PWA for a lot of town of my country (belgium) it's managed by the town halls and the prerequisite is that each user can add to home screen the PWA for his city. 

1st city webapp.lgc.com/{uid}
other city webapp.lgc.com/{uid-v2}
etc....

Than I think the solution it's the multiple manifest for update name, icon, description for SEO etc etc 

Sorry for my english, thanks for your time

**Comment by MaximeScibetta** [comment]
@pi0 Any idea ?

**Comment by pi0** [comment]
@MaximeScibetta I think we would need a dynamic way of generating manifest (per route) i'm working on a refactor for changing the way of manifest serving. Will try to see if we can also support it :)

**Comment by MaximeScibetta** [comment]
Great ! Thanks

**Comment by rikoz** [comment]
@MaximeScibetta As I see, if I'm correct, you have PWA successfully running for your application. well I will be needing some help and guide from you and @pi0 ...
I have done all lighthouse optimizations but seem to be stucked on PWA module (workbox & oneSignal)
![Screenshot from 2019-07-23 05-29-39](https://user-images.githubusercontent.com/6421629/61683075-0a910600-ad0c-11e9-9193-c8033e102bb5.png)
and the two main issues are:
1. the generated "sw.js" in static folder doesn't get registered.
2. One signal importScripts throws me console error as seen here:
![Screenshot from 2019-07-23 05-27-40](https://user-images.githubusercontent.com/6421629/61683182-7a06f580-ad0c-11e9-8571-f6b8666dd4e7.png)

I happen to have missed these configurations somewhere. 
![Screenshot from 2019-07-23 05-42-09](https://user-images.githubusercontent.com/6421629/61683295-f0a3f300-ad0c-11e9-8fbe-16b5f6f2f4f8.png)
![Screenshot from 2019-07-23 05-42-28](https://user-images.githubusercontent.com/6421629/61683306-f8fc2e00-ad0c-11e9-833a-46c45d02b707.png)
I have "OneSignalWorker.js" in my static directory which imports "sw.js" but somehow I don't think it's doing it's job.
![Screenshot from 2019-07-23 05-42-47](https://user-images.githubusercontent.com/6421629/61683382-352f8e80-ad0d-11e9-9e9f-9bc0ba05a0d8.png)

Please help with some guide so i know where I'm missing it.
Thanks

**Comment by MaximeScibetta** [comment]
Hi @rikoz, you're sure your `sw.js` is at the root of your project ? 

When I navigate to `https://deploy.rikozone.com/sw.js?1563830936638`  

<img width="632" alt="Capture d’écran 2019-07-23 à 07 46 05" src="https://user-images.githubusercontent.com/17643602/61685796-0241c680-ad1e-11e9-9028-fe7711341fe8.png">

**Comment by rikoz** [comment]
it's in static folder
![Screenshot from 2019-07-23 07-09-07](https://user-images.githubusercontent.com/6421629/61686893-da9c2f80-ad18-11e9-940c-3e18e3f9b6d6.png)
Do you make use of the oneSignal module? 
Can I see your current nuxt.config.js for workbox?
Also why does importScripts give error? do i need to install a module?

**Comment by MaximeScibetta** [comment]
And it's in your `dist folder` ? 

No I use firebase

This is my workbox config 

```
workbox: {
    swURL: 'firebase-messaging-sw.js'
  },
``` 

my firebase-messaging-sw.js

```
importScripts('sw.js');
importScripts("https://www.gstatic.com/firebasejs/5.9.4/firebase-app.js");
importScripts("https://www.gstatic.com/firebasejs/5.9.4/firebase-messaging.js");
firebase.initializeApp({
  messagingSenderId: "XXXXXXXXXXXX"
});

if (firebase.messaging.isSupported()) {
  const messaging = firebase.messaging()
  messaging.setBackgroundMessageHandler(function(payload) {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    console.log('We are not on app background', payload)
    return registration.showNotification(payload.data.title, {
     body: payload.data.body,
     icon: `./chaudfontaine/icon.png`,
     badge: `./chaudfontaine/icon.png`,
     data: payload.data,
     image: `./chaudfontaine/ios-icon.png`,
   });
  });
  self.addEventListener('notificationclick', function(event) {
    console.log('[firebase-messaging-sw.js] Click on message ', event);
    clients.openWindow(event.notification.data.action);
    event.notification.close();
  });
}
```

**Comment by rikoz** [comment]
First I see you're running on 'spa' **mode**, however i'm running '**universal**' and files are served from the _._nuxt_ folder.
I have wrapped my importScripts around an if statement:
`if (typeof importScripts === 'function') {
  importScripts(
    '/sw.js?1563830936638',
    'https://cdn.onesignal.com/sdks/OneSignalSDK.js'
  )
}`
From what i see, the **sw.js** file generated by oneSignal doesn't come together in the build. So it's not found when loaded.
@pi0 please I need a clearer explanation as to how this works.
pwa and onesignal module generates **an sw.js file which doesn't come on production when I build.**
Do I need to need to include this file in nuxt.config.js workbox configuration??
either in importScripts or swURL
`workbox: {
    swURL: 'sw.js'       // OR
    importScripts: ['sw.js']
}`
Please help thanks

**Comment by rikoz** [comment]
Any feedbacks @MaximeScibetta @pi0

**Comment by MSkred** [comment]
I @pi0, I've an other issue with `@nuxt/pwa` and workbox the dialog for " Add to home screen " is not showing when I've this code 

```
   workbox: {
      cacheAssets: false, // for /*
      offline: false, // for /_nuxt/*
      swURL: 'firebase-messaging-sw.js',
      dev: false
    }
```

But if I commented this all work fine.
