### ISSUE TITLE
Service Worker not registered when hosting in S3 but is Locally

### ISSUE THREAD

**Issue by TheYorkshireDev** [nuxt-community/pwa-module#198]
### Version

[v3.0.0-beta.16](https://github.com/pwa-module/releases/tag/v3.0.0-beta.16)

### Reproduction link

[http://I-can-pass-a-link-privately-to-my-testing-bucket-for-debugging.com](http://I-can-pass-a-link-privately-to-my-testing-bucket-for-debugging.com)

### Steps to reproduce

1. Generate a new nuxtJS app: `npx create-nuxt-app`
2. Add PWA support: `npm i @nuxtjs/pwa` and `['@nuxtjs/pwa', { icon: false }],` to the config file as outline in https://pwa.nuxtjs.org/setup.html
3. Generate static files: `npm run generate`
4. Upload to S3 and enable static web hosting
5. Visit web hosting endpoint and open Chrome developer tools
6. Navigate to the "Application" tab to see service worker not registered

### What is expected ?

I would expect the service worker to be registered when navigating to the "Application" tab in Chrome dev tools. I would also expect running an audit on the "Audits" tab to return a identification of the app as a PWA.

### What is actually happening?

Chrome displays the following message on the Application tab in developer tools: "Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest"

If I locally go into the `dist/` folder and run `python -m SimpleHTTPServer 8080` to create a local webserver and navigate to localhost:8080 the service worker IS registered and everything is working.

### Additional comments?

When I run a NuxtJS PWA app locally the service worker is registered and Chrome lighthouse verifies the app is a PWA, however when I upload the same files to S3 and visit the endpoint, the service worker is not registered and therefore there is no PWA support. For some reason the generated js files are not registering the service worker on S3.

I suspect it is related to the `pwa-module` because the one of the generated JavaScript files from running `npm run generate` has the line which should register the service worker but it does not. Snippet of the function which is from a minified file so may not be very useful:
```
function L() {
            return (L = Object(o.a)(regeneratorRuntime.mark(function t() {
                var e, r, o;
                return regeneratorRuntime.wrap(function(t) {
                    for (; ; )
                        switch (t.prev = t.next) {
                        case 0:
                            if (!(!1 in navigator)) {
                                t.next = 2;
                                break
                            }
                            throw new Error("serviceWorker is not supported in current browser!");
                        case 2:
                            return t.next = 4,
                            n.e(4).then(n.bind(null, 149));
                        case 4:
                            return e = t.sent,
                            r = e.Workbox,
                            o = new r("/sw.js",{
                                scope: "/"
                            }),
                            t.next = 9,
                            o.register();
                        case 9:
                            return t.abrupt("return", o);
                        case 10:
                        case "end":
                            return t.stop()
                        }
                }, t)
            }))).apply(this, arguments)
        }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c146">#c146</a>)</em></sub></div>

**Comment by jayalog** [comment]
Im also facing the same problem. Any solutions for this??

**Comment by TheYorkshireDev** [comment]
Hi @jayalog 

If I remember correctly, service workers only work using HTTP when running locally. When using the static website feature on S3 I believe it only works with HTTP hence it not working for us. 

My solution (which I was planning on doing after initial testing anyway) was to use CloudFront to provide a TLS certificate and therefore HTTPS support for the website. Once in place, my service worker registered fine.

I hope this helps. I am going to close this issue because it is not related to the Nuxt PWA module.

**Comment by jayalog** [comment]
Thank you @TheYorkshireDev
