### ISSUE TITLE
Disable icons or manifest auto generation or overwrite them

### ISSUE THREAD

**Issue by marvinhuebner** [nuxt-community/pwa-module#202]
### What problem does this feature solve?

I'm currently working on a project where I have very strict CI requirements. Unfortunately it's not enough for me to have just one icon as source.

Is there a way to completely disable the generation of the manifest.json and the icons so that i can write them manually?

### What does the proposed changes look like?

Add new options for `manifest` and `icons`, maybe set them simply to `false`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c147">#c147</a>)</em></sub></div>

**Comment by pi0** [comment]
Use this:

```js
{
  modules: {
     ['@nuxtjs/pwa', { icon: false, manifest: false }]
   }
}
```

**Comment by marvinhuebner** [comment]
I could have tried that myself 🙈

But works, thanks!
