### ISSUE TITLE
"Add to Home Screen" dialog box

### ISSUE THREAD

**Issue by gokhancetiner** [nuxt-community/pwa-module#204]
Hello, 

Thanks for the great module !!!

I made the required installation and configuration for nuxt/pwa. After build when i run my project then i run audit tab on chrome developer tools and my application seems to be installable but Add to Home screen dialog box doesn't shown. Do i make extra configuration to see dialog box ? 

Best Regards,

**Comment by briancbarrow** [comment]
I have this same question. Is there any more info on this?

**Comment by woutercouvaras** [comment]
See here:  https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

right at the bottom you'll see the browsers that support this.  The install option will be available on most browsers, but the user will need to know where to find the install/add to home screen option.

**Comment by woutercouvaras** [comment]
Found this too:  https://developers.google.com/web/fundamentals/app-install-banners/  Hopefully it helps?

**Comment by pi0** [comment]
@woutercouvaras YAY! Thanks for the links. If you make a PR adding these links/tip do docs (like a new FAQ section that would be awesome!)

**Comment by woutercouvaras** [comment]
@pi0 I'll do that for sure...just need to get ahead of some work and then I'll give it a bash :)

**Comment by gd4Ark** [comment]
> This issue as been imported as [question](https://cmty.app/nuxt/pwa-module/issues/c151) since it does not respect [pwa-module issue template](https://cmty.app/nuxt/issues/new?repo=pwa-module). Only bug reports and feature requests stays open to reduce maintainers workload.
> If your issue is not a question, please mention the repo admin or moderator to change its type and it will be re-opened automatically.
> Your question is available at https://cmty.app/nuxt/pwa-module/issues/c151.

https://cmty.app/nuxt/pwa-module/issues/c151 I get Server error
