### ISSUE TITLE
Passing `cacheNames` doesn't make any changes to service worker

### ISSUE THREAD

**Issue by spaceninja** [nuxt-community/pwa-module#206]
### Version

[v2.4.0](https://github.com/pwa-module/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/embed/nuxtjs-pwa-cachenames-bug-rqz03](https://codesandbox.io/embed/nuxtjs-pwa-cachenames-bug-rqz03)

### Steps to reproduce

(you can review this codesandbox in production mode here: https://csb-rqz03.netlify.com/ )

Create a Nuxt app. Add `@nuxtjs/pwa`, and deploy the app. Review the `sw.js` file.

Add a `cacheNames` section to the `workbox` config in `nuxt.config.js`. Redeploy the app, and review the `sw.js` file, and see there are no differences.

We added this section to `nuxt.config.js`:

```js
workbox: {
    offlineAnalytics: true,
    cacheNames: {
      prefix: "my-app",
      suffix: "v1",
      precache: "custom-precache-name",
      runtime: "custom-runtime-name"
    }
  },
```

### What is expected ?

I would expect the cache names to changes when I provide a `cacheNames` object.

### What is actually happening?

The cache names do not change.

### Additional comments?

NOTE: The version dropdown doesn't contain v2.6.0 which is the version we're actually using

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c152">#c152</a>)</em></sub></div>

**Comment by spaceninja** [comment]
Note the `offlineAnalytics` option also doesn't seem to have any effect.

**Comment by rikoz** [comment]
This module doesn't seem to have an active response/support.

**Comment by manniL** [comment]
@rikoz 	It's not easy to keep track of all modules and the nuxt core itself 24/7 😉 	

@spaceninja 	have you tried the 3.0.0 beta?

**Comment by spaceninja** [comment]
Oh yes, I forgot to come back and update this… TL;DR: The docs, although they don't say this, are not for the stable version, they're for the 3.0 beta. The features I said weren't working aren't in the 2.6 stable version.

So I guess, feature request: version the docs? ;)

**Comment by manniL** [comment]
@spaceninja 	good point! Would you add a note to the current docs so other ppl won't experience the same issue?

**Comment by Paul-Hebert** [comment]
Thanks for adding the version note @spaceninja !

I wanted to comment for future readers that I found a workaround for the initially reported issue (cacheNames option not working) when using version 2.6.

You can write a custom script that manually updates cache names and then import it into your service worker:

**workbox-customization.js**

```js
/**
 * Define custom cache names.
 * @see https://developers.google.com/web/tools/workbox/guides/configure-workbox
 */
workbox.core.setCacheNameDetails({
  prefix: 'my-app',
  suffix: 'v1',
  precache: 'custom-precache-name',
  runtime: 'custom-runtime-name'
});
```

**nuxt.config.js**
```js
module.exports = {
  workbox: {
    importScripts: ['workbox-customization.js'],
  }
};
```

Thanks for Nuxt PWA!
