### ISSUE TITLE
Background Sync

### ISSUE THREAD

**Issue by lhp0** [nuxt-community/pwa-module#216]
I am trying to build a nuxt PWA with background sync feature, i created background_sync.js  under /static folder with this piece of code copied from Google Workbox Doc.
```
if (workbox) {
    console.log(`Yay! 'background_sync.js' is loaded 🎉`);

    const bgSyncPlugin = new workbox.backgroundSync.Plugin('myQueueName', {
        maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
    });

    workbox.routing.registerRoute(
        /\/api\/.*/,
        new workbox.strategies.NetworkOnly({
            plugins: [bgSyncPlugin]
        }),
        'GET'
    );

} else {
    console.log(`Boo! 'background_sync.js' didn't load 😬`);
}
```

i imported this script file in nuxt.config.js 
{
   workbox: { importScripts: ["background_sync.js"] }
}
but i got this error when i deploy this SPA to production.
![Screenshot 2019-07-29 at 11 41 28 AM](https://user-images.githubusercontent.com/25162549/62020568-14c47000-b1f6-11e9-9ee7-40655c0c2785.png)

**Comment by lhp0** [comment]
fix using this work around,
https://github.com/nuxt-community/pwa-module/issues/196
thanks for your time

**Comment by rcheung9** [comment]
@lhp0 Hi, what work around are you referring to? If possible, can you show a bit of your config / code? Thanks.
