### ISSUE TITLE
Enable rangeRequests documentation needs tweaking

### ISSUE THREAD

**Issue by samboylett** [nuxt-community/pwa-module#220]
### What problem does this feature solve?

There is a tiny issue with the documentation at https://pwa.nuxtjs.org/modules/workbox.html#enable-rangerequests

The Regex begins with `.*` so the route will match request to third party services as well as local files. By default the nuxt PWA does not cache third party / CORS requests, so this example is a bit misleading as it will bring video files into the service worker which were not cached before.

See https://developers.google.com/web/tools/workbox/modules/workbox-routing for more info on workbox routing but essentially matching the url from the beginning lets you match CORS requests, otherwise it will only match local requests.

### What does the proposed changes look like?

change the example to:

```
workbox.routing.registerRoute(
  /\.(mp4|webm)/,
  workbox.strategies.cacheFirst({
    plugins: [
      new workbox.rangeRequests.Plugin(),
    ],
  }),
  'GET'
);
```

(i.e. remove the `.*`)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c161">#c161</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Would you please make a pull request? ☺️

**Comment by ricardogobbosouza** [comment]
This should have been closed
