### ISSUE TITLE
PWA icons option iconFileName 

### ISSUE THREAD

**Issue by azulkipli** [nuxt-community/pwa-module#243]
### Version

[v3.0.0-beta.19](https://github.com/pwa-module/releases/tag/v3.0.0-beta.19)

### Reproduction link

[https://codesandbox.io/s/nuxt-pwa-icon-custom-vi4dz](https://codesandbox.io/s/nuxt-pwa-icon-custom-vi4dz)

### Steps to reproduce

clone the codesanbox,
install node dependencies with executing `yarn`
execute `yarn generate:staging` to build Nuxt prerender SPA

### What is expected ?

Based on this documentation the pwa module should be generate icon based on filename

https://pwa.nuxtjs.org/modules/icon.html#options

but it just generated default `icon.png`

### What is actually happening?

I try the option with using different file name `icon_dev.png` if `NODE_ENV=staging` in the `iconFileName`

Nuxt with pwa module just generate default icon.png even I wrote different icon file name.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c176">#c176</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @azulkipli
You are using the wrong option is `icon` non `icons`
See https://pwa.nuxtjs.org/modules/icon.html

```js
// nuxt.config.js
pwa: {
  icons: { <--------- use `icon`
    /* icon options */
    iconFileName: process.env.NODE_ENV==='staging' ? 'icon_dev.png': 'icon.png'
  }
}
```

**Comment by azulkipli** [comment]
Oh sorry my mistake didnt notice that.

Thank you
