### ISSUE TITLE
Disable add to home screen

### ISSUE THREAD

**Issue by LeCoupa** [nuxt-community/pwa-module#247]
Is there a way to disable the add to home screen banner to appear on mobile? I might be blind, but I can't find the [options for this here](https://pwa.nuxtjs.org/modules/workbox.html#options).

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c181">#c181</a>)</em></sub></div>

**Comment by svale** [comment]
Hi. There are a set of criteria that have to be met for the home screen banner to appear on mobile. One is that the manifest display mode must be  Standalone, Fullscreen, Minimal-UI.  So you should be able to disable the banner by setting this to `browser` in you nuxt.config:
```js
{
   manifest: {
      display: 'browser'
  },
}
```

**Comment by pi0** [comment]
@svale Thank :) If you wish, can you please make a PR for adding to docs?

**Comment by svale** [comment]
@pi0 Sure - need to verify again first though :) 

Perhaps as an addition to https://pwa.nuxtjs.org/modules/workbox.html#hooking-on-service-worker-registration-life-cycle I'll put in on my list of todos.

**Comment by LeCoupa** [comment]
I can confirm, it is working: https://www.growthbunker.dev/

Thank you @svale :)
