### ISSUE TITLE
AutoRegister false not working

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nuxt-community/pwa-module#26]
Iam implementing a custom notification with vue . Everything works fine but the permissionPrompt is displaying while the page loads ... Any help required.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c21">#c21</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This should be fixed starting `3.0.0-beta` :)
