### ISSUE TITLE
AMP integration, PWAMP?

### ISSUE THREAD

**Issue by hackuun** [nuxt-community/pwa-module#27]
Hello. Somebody interested in AMP integration? It's combine PWA and AMP.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c20">#c20</a>)</em></sub></div>

**Comment by MarkHjorth** [comment]
That would be amazing!

**Comment by ahmedfaical** [comment]
I'm interested too

**Comment by kostia7alania** [comment]
me too!
