### ISSUE TITLE
Why documentation say sw.* should place in gitignore?

### ISSUE THREAD

**Issue by designy** [nuxt-community/pwa-module#280]
https://cmty.app/nuxt/pwa-module/issues/c207

**Comment by manniL** [comment]
Because it is auto-generated during the build. And generated content should (usually) not be checked into git.

**Comment by designy** [comment]
so, should be place generated sw.js file into the server manually? because after the build, browser needs sw.js be in the root, but the request has 404 status and not found.

**Comment by designy** [comment]
> Because it is auto-generated during the build. And generated content should (usually) not be checked-in into git.

so, should be place generated sw.js file into the server manually? because after the build, browser needs sw.js be in the root, but the request has 404 status and not found.

**Comment by pi0** [comment]
@designy Indeed. Depending on your deployment type, static dir files should be also put into server (except if using nuxt generate)

**Comment by designy** [comment]
we used to run nuxt build then commit and push generated files to server.
It seems we should transfer the sw.js file to server manually. 
@pi0 thank you Pooya.
