### ISSUE TITLE
Default iconSrc should use assets, not static

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt-community/pwa-module#29]
Putting it in `static` cause it to be copied to the destination, creating a stale file for most cases. Instead `assets` should be preferred.

A fallback could be added for backward compatibility.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c19">#c19</a>)</em></sub></div>

**Comment by pi0** [comment]
will be landed in 3.0.0-beta.1
