### ISSUE TITLE
unable to remove sw.js from critical rendering path

### ISSUE THREAD

**Issue by MUMUKSHMEGHWAL** [nuxt-community/pwa-module#298]
I have used https://github.com/nuxt-community/pwa-module.
I want to remove sw.js from critical rendering path to improve performance but unable to do so.

**Comment by pi0** [comment]
Hi @MUMUKSHMEGHWAL. You can disable it by setting `pwa.workbox: false` inside `nuxt.config` but you will lose benefit of having a PWA app.
