### ISSUE TITLE
AppleStatusBarStyle options

### ISSUE THREAD

**Issue by jhull** [nuxt-community/pwa-module#338]
The following isn't applying the proper meta tag to my PWA:

```
pwa: {
    meta: {
      appleStatusBarStyle: 'black-translucent'
    }
  }
```

I notice in another issue, someone just put a color in there -- what are the possible options there?

**Comment by DraftProducts** [comment]
Hi @jhull, this feature works correctly, check that you have activated the mobileAppIOS option.
It's a required option: 
![image](https://user-images.githubusercontent.com/29425008/93940705-4323d980-fd2d-11ea-8ec9-62a86044bedf.png)

**Comment by ninest** [comment]
I created a pull request to provide the options and requirements of this property (https://github.com/nuxt-community/pwa-module/pull/360/). Hope it helps someone in the future

**Comment by pi0** [comment]
For convince, with next version it will be possible to use `appleStatusBarStyle` without setting `mobileAppIOS` too. (b0f226aadeee50b47790ac064852b444e33d9b95)
