### ISSUE TITLE
Incorrect publicPath in the manifest.json

### ISSUE THREAD

**Issue by awronski** [nuxt-community/pwa-module#34]
Hi!

In the generated `manifest.xxxx.json` the path is has Double `//`:
```js
"publicPath":"//_nuxt/"
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c22">#c22</a>)</em></sub></div>

**Comment by MikeSheward** [comment]
Can confirm, this is still a thing. Weather it causes any issues or not i'm unsure, but it's still a thing in 2.0.8.

**Comment by pi0** [comment]
Thanks for report @awronski, @MikeSheward. With 4afaa673cba141ac8e31a890980ca191e86e194c commit (Landing in `3.0.0-beta.1`) we now use posix path to join url parts and resolve this issue.

**Comment by MikeSheward** [comment]
Thanks!
