### ISSUE TITLE
problem with meta

### ISSUE THREAD

**Issue by frederic117** [nuxt-community/pwa-module#340]
Hello
I don't understand what is wrong with my head meta tag:
Looking in the console it seems good but this is not read by meta anlyser:
exemple: 
https://www.footfoot.co/news/babble/5f4a08a95c8269002a913805

meta data-n-head="ssr" data-hid="twitter:creator" name="twitter:creator" property="twitter:creator" content="@InsidersFoot">meta data-n-head="ssr" data-hid="og:type" name="og:type" content="website"><meta data-n-head="ssr" data-hid="description" name="description" content="
Houssem Aouar est passé par tous les états. Jeudi, le milieu de terrain était aux anges. Pour la première fois, Didier Deschamps le convoquait p (...) - Footmercato">
meta data-n-head="ssr" data-hid="keywords" name="keywords" keywords="
Houssem Aouar est passé par tous les états. Jeudi, le milieu de terrain était aux anges. Pour la première fois, Didier Deschamps le convoquait p (...) - Footmercato">
meta data-n-head="ssr" data-hid="og:title" property="og:title" content="EdF : Rudi Garcia déçu pour Houssem Aouar"><meta data-n-head="ssr" data-hid="og:url" property="og:url" content=" https://www.footfoot.co/news/babble/5f4a08a95c8269002a913805">
meta data-n-head="ssr" data-hid="" property="" content=""><meta data-n-head="ssr" data-hid="og:image" property="og:image" content="https://assets-fr.imgfoot.com/media/cache/1200x675/houssem-aouar-france.jpg">
meta data-n-head="ssr" data-hid="og:description" property="og:description" content="
Houssem Aouar est passé par tous les états. Jeudi, le milieu de terrain était aux anges. Pour la première fois, Didier Deschamps le convoquait p (...) - Footmercato">
meta data-n-head="ssr" data-hid="twitter:card" name="twitter:card" property="twitter:card" content="summary_large_image">
meta data-n-head="ssr" data-hid="" name="" property="" content="">
meta data-n-head="ssr" data-hid="twitter:site" name="twitter:site" property="twitter:site" content="@footfoot.co"><meta data-n-head="ssr" data-hid="twitter:title" name="twitter:title" property="twitter:title" content="EdF : Rudi Garcia déçu pour Houssem Aouar">
meta data-n-head="ssr" data-hid="twitter:description" name="twitter:description" property="twitter:description" content="
Houssem Aouar est passé par tous les états. Jeudi, le milieu de terrain était aux anges. Pour la première fois, Didier Deschamps le convoquait p (...) - Footmercato">
meta data-n-head="ssr" data-hid="twitter:image" name="twitter:image" property="twitter:image" content="https://assets-fr.imgfoot.com/media/cache/1200x675/houssem-aouar-france.jpg">

and if i use this tool : 
http://analyzer.metatags.org/
it seems to have the default meta.

Please can someone help me ?

**Comment by PGLongo** [comment]
How have you fixed this?
