### ISSUE TITLE
[WARN] You are using a low quality icon, use icon png

### ISSUE THREAD

**Issue by pi0** [nuxt-community/pwa-module#341]
reported by @liyasthomas (https://github.com/nuxt-community/pwa-module/issues/259#issuecomment-674545622 https://github.com/nuxt-community/pwa-module/issues/259#issuecomment-674552622) @thiscodes4u (https://github.com/nuxt-community/pwa-module/issues/259#issuecomment-684122810) and @zorca. It seems introduced by #258. Still didn't try to reproduce but seems a valid case or at least something not properly documented.

**Comment by ricardogobbosouza** [comment]
I tested it locally and it is working.
May be having a problem generating icons from `icon.png` https://github.com/nuxt-community/pwa-module/blob/master/lib/icon/module.js#L130

**Comment by ricardogobbosouza** [comment]
@liyasthomas 
If you can share some code, it would be of great help.

**Comment by ricardogobbosouza** [comment]
@pi0 problem on `spa` mode
https://github.com/nuxt-community/pwa-module/blob/master/lib/icon/module.js#L13
`_emitAssets` not called.

**Comment by ricardogobbosouza** [comment]
Removing this line solves the problem
https://github.com/nuxt-community/pwa-module/blob/master/lib/meta/module.js#L11

**Comment by ricardogobbosouza** [comment]
Is it okay to just run on the `build: before` hook?

**Comment by mtltechtemp** [comment]
any update on this guys?

**Comment by pi0** [comment]
7a1e77384eb88f0886180bc784efa242ae59e5ad
