### ISSUE TITLE
Service worker file sw.js is missing on Vercel after fast re-deploys with target static

### ISSUE THREAD

**Issue by kfrederix** [nuxt-community/pwa-module#352]
This issue is related to the combination of:
- new `target: static` improvements introduced in nuxt 2.14.0
- this pwa module, which generates `sw.js` during webpack build
- static hosting platforms like Vercel

# Versions
- nuxt: 2.14.5
- node: 12.x

### Steps to reproduce
1. Create new nuxt app with `target: 'static'`
2. Add @nuxtjs/pwa module
3. Deploy to vercel (using build command: `nuxt generate`)
4. Observe sw.js is there (= ok)
5. Trigger web hook for re-deploy (will skip webpack build)
6. Observe sw.js is missing (= not ok)

### What is Expected?
`sw.js` should be present after fast generate using previous build cache (skipping webpack build).

### What is actually happening?
`sw.js` is missing after fast generate using previous build cache (skipping webpack build).

So it seems to me like the generated `sw.js` file is not included in the build cache which is stored on Vercel, and therefore it will get missed when doing fast re-deploys which skip the webpack build step.

Not sure if this issue belongs here, or rather in the actual nuxt.js repo...

**Comment by codeofsumit** [comment]
Our sites are starting to fail - is this related?

![image](https://user-images.githubusercontent.com/2399810/95305614-82523e80-0886-11eb-94e8-93aee7f97e96.png)

**Comment by pi0** [comment]
@codeofsumit nope please see #365 (fixed in [v3.1.1](https://github.com/nuxt-community/pwa-module/releases/tag/v3.1.1))

**Comment by pi0** [comment]
Hi. Sorry for inconveniences. This issue should be resolved by [v3.2.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.2.0)

**Comment by kfrederix** [comment]
Thanks @pi0 !
