### ISSUE TITLE
(PWA - Vercel) sw.js not found 

### ISSUE THREAD

**Issue by Ratatinator97** [nuxt-community/pwa-module#367]
Hello,
I built a great app thanks to Nuxtjs and Buefy. 
But I have an issue deploying the PWA app to Vercel. It doesn't appear as a PWA and the `sw.js` can't be loaded.

You can have a look at the source code [here](https://github.com/Ratatinator97/PicTalk-Frontend/tree/pwa). In the repo you will find the `now.js`, the `package.json` and the `nuxt.config.js`. You can also have a look at the web app online at [www.pictalk.xyz](https://www.pictalk.xyz). If you go to developers tools, you will se that `sw.js` can't be loaded.

Many thanks to the Nuxtjs, VueJS community and devs !

**Comment by pi0** [comment]
Hi @Ratatinator97. This is dup of #352 we are aware of this issue and looking for a workaround

**Comment by Ratatinator97** [comment]
> Hi @Ratatinator97. This is dup of #352 we are aware of this issue and looking for a workaround

I already saw, that issue.
I don't have a static app, it's a `ssr:false` and `npm run build` app. Not a static app.

**Comment by pi0** [comment]
Hi. Sorry for inconveniences. This issue should be resolved by [v3.2.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.2.0)
