### ISSUE TITLE
meta.merge.js file error

### ISSUE THREAD

**Issue by ReyhaneNasiri** [nuxt-community/pwa-module#369]
Hi, I am using "nuxt": "^2.0.0", and "@nuxtjs/pwa": "^3.0.0", but I am getting this error: "export 'mergeMeta' was not found in './meta.merge'
![Screen Shot 1399-07-19 at 11 58 29 AM](https://user-images.githubusercontent.com/61539381/95650373-1c68ef80-0af0-11eb-8e93-30a510a061df.png)
I searched a lot but I didn't find any solution!!!

**Comment by pi0** [comment]
Hi @ReyhaneNasiri Sorry for inconveniences. This issue should be resolved by [v3.2.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.2.0). Please reopen if still exists after upgrading. (i would suggest to clean `node_modules` and `yarn.lock`/`package.lock.json` as well)

**Comment by kidbai** [comment]
I am using "nuxt": "^2.0.0", and "@nuxtjs/pwa": "^3.2.2". I am getting the same warning，but it built is ok. Is this warning ok ?

![image](https://user-images.githubusercontent.com/1251979/98645227-a1079180-236c-11eb-9cc5-bb8662f64e21.png)

**Comment by pi0** [comment]
@kidbai Actually first warning sounds something is wrong. Do you mind making new issue and sharing nuxt.config as well?
