### ISSUE TITLE
Workbox Broadcast Cache Update usage

### ISSUE THREAD

**Issue by incrediblink** [nuxt-community/pwa-module#37]
Hi! I want to notify my clients to upgrade their application when the website is updated. I noticed that there is a Workbox module called [Workbox Broadcast Cache Update](https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-cache-update). Is there any standard way to use it on Nuxt pwa?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c26">#c26</a>)</em></sub></div>

**Comment by msgeissler** [comment]
I would like to know the same. Even overriding the default runtime caching routes does not work, as you cannot add the plugin as a strategy option.
It throws a `ReferenceError: workbox is not defined` or `ReferenceError: self is not defined` when I require workbox-sw inside nuxt.config.js.

Is there actually a solution for using a plugin in a strategy option?

**Comment by creazy231** [comment]
I would like to know the same. Currently I try to implement a workaround by calling a version number from a file and compare it to a version number in the local storage.

**Comment by creazy231** [comment]
Well, some weeks ago a found a solution to inform my clients to update the application by clicking on a button but my solution wasn't as easy as I could explain it to someone else.

All in all I found out, that the PWA uses workbox-sw to manage updates. It takes some time (some hours) and the sw recognize, that there is an other version number of the nuxt files and reloads the page on its own. That means that your users won't get your updates imminently but after some hours everyone should have the update.

Hope that helps. Took me several hours to find that out.

**Comment by MrJmpl3** [comment]
More information please, or example code

**Comment by pi0** [comment]
You can use `cachingExtensions` to enable the plugin. Similar comment https://github.com/nuxt-community/pwa-module/issues/64#issuecomment-422324895.
