### ISSUE TITLE
start_url did respond but not via service worker

### ISSUE THREAD

**Issue by shadow81627** [nuxt-community/pwa-module#372]
I am trying to figure out why my PWA isn't being installed on android as a [WebAPK](https://developers.google.com/web/fundamentals/integration/webapks) any more. The add to home screen is just creating a shortcut rather than the WebAPK. I ran a lighthouse audit that is erroring on start_url does not respond with a 200 when offline. 

I am using Vercel for hosting so it could be an issue related to #367 #352 but it seems like the service worker is being found and is running.

![Screenshot 2020-10-13 152918](https://user-images.githubusercontent.com/21211734/95819318-116cc400-0d69-11eb-8b22-3be13a49384e.png)

**Comment by pi0** [comment]
Hi @shadow81627 this issue is resolved with [v3.2.1](https://github.com/nuxt-community/pwa-module/releases/tag/v3.2.1). We add a query string to `start_url` to be able detecting standalone ATH starts. Seems latest lighthouse audit needed to explicitly precache exact URL

**Comment by RauppRafael** [comment]
Hi @pi0 the commit 27e19a04d6f2b14943a0bb4a9b7414382591d4e0 seems to be causing issue #375 as it is not adding the revision to the file

**Comment by xrei** [comment]
Why do you need to add `start_url` to precache ? I think its related to bug that i have #384

**Comment by dseeker** [comment]
having the same problem with 3.2.2

**Comment by pi0** [comment]
Hi. This issue should be gone with [3.3.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.3.0).

**Comment by simonmaass** [comment]
the issue is not gone in 3.3.0!

**Comment by pi0** [comment]
@simonmaass Seems regression was back since adding revision also to start_url as query. Would you please try 3.3.2?

**Comment by simonmaass** [comment]
@pi0 yeh works now
