### ISSUE TITLE
[3.2.0] icons not generated for `nuxt dev`

### ISSUE THREAD

**Issue by dappiu** [nuxt-community/pwa-module#373]
Version 3.1.2 is still fine, but upgrading to 3.2.0 or 3.2.1 I see that icons are no more generated using "yarn dev" on Nuxt 2.14.6 with target "server". No warning or errors in output. Link to the icon is there but the file is non existent. 

I have my `icon.png` in static folder and using default options for icon module. You will have to delete cache folder in node_modules to see that the icons are not generated starting from version 3.2.0.

**Comment by pi0** [comment]
Hi @dappiu. Is it possible if you can share you project with me or providing `nuxt.config`?

**Comment by pi0** [comment]
Thanks for reporting. Should be fixed in [v3.2.2](https://github.com/nuxt-community/pwa-module/releases/tag/v3.2.2)
