### ISSUE TITLE
No manifest or icons generated, only sw.js

### ISSUE THREAD

**Issue by Yiddishe-Kop** [nuxt-community/pwa-module#374]
I have a `nuxt-content-docs` project, and I'm following the docs [here](https://content.nuxtjs.org/themes/docs#static) by adding an `icon.png` to the `static` folder.

But after running `generate` or deploying to Vercel, the manifest & icons aren't generated (it has the default Nuxt icon), only `sw.js` is generated.

Any ideas?

Thanks! 😀

Here is the repo: https://github.com/Yiddishe-Kop/laravel-commerce-docs

**Comment by pi0** [comment]
Hi 👋 Checking your lock file, pwa is installed at 3.1.2. Issue is fixed with latest (3.2.2). Can you please run `yarn upgrade @nuxtjs/pwa`?

**Comment by Yiddishe-Kop** [comment]
I upgraded `"@nuxt/content-theme-docs": "^0.7.2",`, and now it's working.

Thanks! 😀
