### ISSUE TITLE
Workbox is precaching URLs without revision info

### ISSUE THREAD

**Issue by RauppRafael** [nuxt-community/pwa-module#375]
Hi, after installing this module to my project the following warning is logging to my console:

```
workbox-precaching.prod.js:1 
Workbox is precaching URLs without revision info: /?standalone=true
This is generally NOT safe. Learn more at https://bit.ly/wb-precache
```

How can I fix it?

**Comment by xrei** [comment]
Same here. because of it pwa gets cached version instead of server-rendered one.

**Comment by RauppRafael** [comment]
@pi0 can you take a look at 27e19a0 to fix this warning?

**Comment by Divlo** [comment]
Still no way to fix it?

**Comment by fabiofdsantos** [comment]
ping @pi0

**Comment by pi0** [comment]
please try 3.3.x (https://github.com/nuxt-community/pwa-module/releases/tag/v3.3.0)

**Comment by jengel3** [comment]
Can confirm that the above release fixes it!

**Comment by Jandoria** [comment]
I don't get the console errors anymore but I still get this one from Lighthouse:
`no-response: no-response :: [{"url":"myurl"}] at Object.handle (https://cdn.jsdelivr.net/npm/workbox-cdn@5.1.4/workbox/workbox-strategies.prod.js:1:1883)`

**Comment by pi0** [comment]
@Jandoria please see https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-665722983. There are many reasons no-response happens. It is basically when workbox cannot fetch the remote endpoint. If you have a public deployment i can try to investigate more..

**Comment by Jandoria** [comment]
Sorry @pi0, I didn't see your response. I just tried with workbox clientsClaim: false and it worked for me. Thank you! :)
