### ISSUE TITLE
nuxtServerInit is not called in route cached by workbox

### ISSUE THREAD

**Issue by xrei** [nuxt-community/pwa-module#384]
It seems when i visit route service worker sent me cached page and code inside nuxtServerInit action haven't been called

**Comment by pi0** [comment]
Hi @xrei. Actually more context is required to investigate more. But if it is not resolved with 3.3.0 please feel free to reopen with a reproduction link or code.

**Comment by gmatkowski** [comment]
Have You found any solution to solve this issue?

**Comment by Andrevoks** [comment]
still have same issue with start page
