### ISSUE TITLE
Regression: package.json name is used as title in titleTemplate

### ISSUE THREAD

**Issue by trygveaa** [nuxt-community/pwa-module#387]
As of version 3.1.0 if a page doesn't specify a title, the name from package.json is used in the titleTemplate config in the head config, either as the `%s` placeholder or the argument sent to the function. Previously, an empty string was used.

The reason this is a problem is that we have this function as the titleTemplate:

    titleTemplate: (titleChunk) =>
      (titleChunk ? `${titleChunk} | ` : '') + 'App name'

Which allows us to have "Sub page | App name" if a page specifies "Sub page" as the title, and just "App name" if a page doesn't specify a title. Now "name from package.json | App name" is used instead.

This was changed in #363. Is this change intentional?

**Comment by trygveaa** [comment]
Hm, that didn't work for me, but setting `head.title = ''` seems to work. Thanks.

**Comment by alejandroyunes** [comment]
app: {
  head: {
    htmlAttrs: { lang: 'es' },
    title: 'default title', 
    titleTemplate: '%s',
  },

**Comment by alejandroyunes** [comment]
I was able to remove the key name from the package.json with the titleTemplate below:

`app: { head: { htmlAttrs: { lang: 'es' }, title: 'default title',  titleTemplate: '%s', }, }`
