### ISSUE TITLE
iOS app icon with transparent background showing black background on device

### ISSUE THREAD

**Issue by charlie0077** [nuxt-community/pwa-module#392]
I have added an icon to my app. It has rounded edges and no background. The problem is that when I run an app on my device (iPhone 5) the icon has a black background behind the edges as if it wasn't transparent. Any solutions?

https://stackoverflow.com/questions/22858501/ios-app-icon-with-transparent-background-showing-black-background-on-device

I do want to transparent color, because it is much better in desktop and android. If pwa-module allow users to specify a background color per device type, that would be great.

**Comment by charlie0077** [comment]
How do you work around this?

**Comment by twnaing** [comment]
Manifest file accepts multiple entries for icons like this

```json
{
  …
  "icons": [
    …
    {
      "src": "path/to/regular_icon.png",
      "sizes": "196x196",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "path/to/maskable_icon.png",
      "sizes": "196x196",
      "type": "image/png",
      "purpose": "maskable" // <-- New property value `"maskable"`
    },
    …
  ],
  …
}
```

But official [nuxtjs/pwa icon modules doc](https://pwa.nuxtjs.org/icon) only shows accepting one options for generating icons. 

```
pwa: {
  icon: {
    /* icon options */
  }
}
```

It does not describe how can we use with multiple icons.

**Comment by ram-you** [comment]
> [Manifest file accepts multiple entries for icons](https://web.dev/maskable-icon/) like this
> 
> ```js
> {
>   …
>   "icons": [
>     …
>     {
>       "src": "path/to/regular_icon.png",
>       "sizes": "196x196",
>       "type": "image/png",
>       "purpose": "any"
>     },
>     {
>       "src": "path/to/maskable_icon.png",
>       "sizes": "196x196",
>       "type": "image/png",
>       "purpose": "maskable" // <-- New property value `"maskable"`
>     },
>     …
>   ],
>   …
> }
> ```
> 
> But official [nuxtjs/pwa icon modules doc](https://pwa.nuxtjs.org/icon) only shows accepting one options for generating icons.
> 
> ```js
> pwa: {
>   icon: {
>     /* icon options */
>   }
> }
> ```
> 
> It does not describe how can we use with multiple icons.

Hi @twnaing 
Your remark is entirely relevant. Did you find a solution?
