### ISSUE TITLE
WARNING in ./.nuxt/pwa/meta.js

### ISSUE THREAD

**Issue by kidbai** [nuxt-community/pwa-module#393]
This issue is from here [meta.merge.js file error #369](https://github.com/nuxt-community/pwa-module/issues/369).

The build is warning after insert these nuxtjs/pwa modules config.And diff nuxt.config is:
`
  pwa: {
    manifest: {
      name: 'xxx',
      lang: 'zh',
      description: 'xxx'
    }
  },
  buildModules: [
    '@nuxtjs/pwa'
  ],
`

The project use `nuxt build`

**Comment by ahurov** [comment]
same error @pi0 
![image](https://user-images.githubusercontent.com/25090332/100347644-5e8db800-2fee-11eb-8807-7b255bca598d.png)
![image](https://user-images.githubusercontent.com/25090332/100347631-59306d80-2fee-11eb-98cf-36140ced09b6.png)
![image](https://user-images.githubusercontent.com/25090332/100347597-4cac1500-2fee-11eb-8597-9f73d55a70dd.png)

**Comment by pi0** [comment]
Hi. I believe this issue should be gone with 3.3.0 refactors. Would be appreciated if can confirm :)
