### ISSUE TITLE
Unable to detect update in sw.js out of the box

### ISSUE THREAD

**Issue by andrewspy** [nuxt-community/pwa-module#401]
This is a follow up to #239.

Since pwa-module always generate the same "sw.js" out of the box, and workbox is unable to detect the unmodified "sw.js", I think a note should be put in "Refresh to Update Notification" example in [pwa.nuxtjs.org/workbox](https://pwa.nuxtjs.org/workbox/#refresh-to-update-notification), i.e.

> `event.isUpdate` can only work when "sw.js" is modified for every build.

The simplest workaround would be to put a signature in `workbox.config`, however this may polute `workbox.config`,

```js
    workbox: {
      config: {
        ':signature': Date.now(), // generate new sw.js for each build
      },
    },
```

A more proper way would be to append a timestamp in `sw.js` in the build chain, but it may be unnecessary complicated for beginners.

**Comment by pi0** [comment]
Hi @andrewspy. Starting with [3.3.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.3.0), a revision (random per-build) is added to `sw.js`. I hope it fixed issue but if not please reopen.
