### ISSUE TITLE
Add custom header to request

### ISSUE THREAD

**Issue by AkioSarkiz** [nuxt-community/pwa-module#402]
Hello. I want add custom header to request. Can i make it?  
Example:   
i send request to server https://example.com with header Auth: true  
is it possible?

**Comment by pi0** [comment]
Hi @AkioSarkiz i think it would be possible using http client (@nuxtjs/axios or @nuxtjs/http). How are you currently making requests?

**Comment by AkioSarkiz** [comment]
@pi0 I use axios, but now browser auto send request. I am creating an img component and pasting a link. This image is protected and cannot be obtained without authorization.
Something like <img: src = "link>

**Comment by AkioSarkiz** [comment]
i send request axios and encode response to base64. Put it to src attribute. Profit ~
