### ISSUE TITLE
Handle icon.webp

### ISSUE THREAD

**Issue by slntopp** [nuxt-community/pwa-module#405]
I'm getting fatal error(picrel), if trying to use webp image as icon.
```json
{
 pwa: {
  icon: {
   fileName: "icon.webp"
  }
 }
}
```

<img width="571" alt="Screenshot 2020-11-30 at 13 22 13" src="https://user-images.githubusercontent.com/32666515/100614085-dc670180-3315-11eb-9842-22014f34e3fd.png">

**Comment by pi0** [comment]
Hi @slntopp. It is not possible yet since we need a more advanced library to support SVG and Webp formats. Please follow up #398

**Comment by slntopp** [comment]
Got it, thanks
