### ISSUE TITLE
Missing standalone url parameter for iOS

### ISSUE THREAD

**Issue by cswkim** [nuxt-community/pwa-module#439]
I just upgraded to `3.3.5` from `3.0.0` and I noticed when I try to "Add to Homescreen" from iOS (`14.4`) Safari the url does not have the `?standalone=true` parameter appended any longer. Subsequently, the shortcut does not use my `static/icon.png` (uses a screenshot of the page instead) and the address bar is still there.

**Comment by cswkim** [comment]
Nevermind, might have been some kind of caching issue? I checked again later and no issues.

**Comment by 4KDA** [comment]
what's the solution?
