### ISSUE TITLE
Add package in nuxtjs README

### ISSUE THREAD

**Issue by amazzoccone** [nuxt-community/pwa-module#47]
This template package should be in https://github.com/nuxt/nuxt.js/blob/dev/README.md with the others (starter, express, koa, etc)!
If you want i could make a PR for them to added, but it seemed right to first propose it here.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c33">#c33</a>)</em></sub></div>

**Comment by manniL** [comment]
The @nuxt-community account is listed in the README. That should suffice IMO.

**Comment by pi0** [comment]
@amazzoccone Thanks for care. I agree with @manniL. PWA is something important and i use it in almost all personal projects but we have limited space for README so linking to modules and community would be enough IMO.
