### ISSUE TITLE
Example for custom workbox cache

### ISSUE THREAD

**Issue by Krystus** [nuxt-community/pwa-module#5]
@pi0 can you provide example for customizing workbox ServiceWorker cache for cdn media and external API requests?

**Comment by derekshull** [comment]
Same question here.

**Comment by pi0** [comment]
https://github.com/nuxt-community/pwa-module#adding-custom-runtimecaching-items-for-cdn

**Comment by silverbackdan** [comment]
Updated link is https://pwa.nuxtjs.org/modules/workbox.html
