### ISSUE TITLE
Service worker exposes API keys

### ISSUE THREAD

**Issue by jareko999** [nuxt-community/pwa-module#505]
It seems concerning the `firebase-auth-sw.js` file exposes API keys (displayed in the file and in dev tools). Is this normal? Is it safe to have this file in production? I can't seem to `.gitignore` the file... Here's my setup in my `nuxt.config`:

```
 pwa: {
    workbox: {
      importScripts: ["/firebase-auth-sw.js"],
      // by default the workbox module will not install the service worker in dev environment to avoid conflicts with HMR
      // only set this true for testing and remember to always clear your browser cache in development
      dev: false,
    },
  },
```

**Comment by danielroe** [comment]
This may be helpful: https://firebase.google.com/docs/projects/api-keys

**Comment by jareko999** [comment]
Thanks. I guess as long as they are protected with security rules in firebase, exposing them isn’t a risk.
