### ISSUE TITLE
How to test the installation and download of local localhost:3000 with chrome brower？

### ISSUE THREAD

**Issue by otary** [nuxt-community/pwa-module#516]
After compiling, packaging and publishing, I can click on the URL bar of the Chrome browser to download, but the download button cannot be displayed in the URL bar in the local locahost:3000 state. How can I solve it?

**Comment by deeneshchowdhary** [comment]
Hi @otary ,  I believe you will also need https for the pwa to work. I have had the same issue. But once you deploy the app to a domain with https, you will get the download option in chrome.

**Comment by otary** [comment]
thanks
