### ISSUE TITLE
How to use meta for pages?

### ISSUE THREAD

**Issue by nikkanetiya** [nuxt-community/pwa-module#52]
Hello,

As per default options og:title, og:description will be set as per the package.json or from nuxt.config, but if set the title & description from page the og:title & og:description remains the same, is there any options by which it will take default values for og:title from title & og:description from description from pages?

```
head () {
  return {
    title: `Foo`,
    meta: [
      {
        hid: 'description',
        name: 'description',
        content: 'page foo'
      }
    ]
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c31">#c31</a>)</em></sub></div>

**Comment by manniL** [comment]
Unfortunately not. You need to set them all manually on "page level" using the head function as you currently do. You can also write a function that'd do that for you (like, it takes title and description and sets og tags for you). I've written an "advanced" function that works with i18n as well [here](https://github.com/Developmint/developmint.de/blob/master/plugins/vue-prototype-extensions.js) if you want to take a look.

**Comment by nikkanetiya** [comment]
Something slimier to that, I am doing at moment.

**Comment by JDomleo** [comment]
Is there any progression on this? It would be great to update the `description` for a specific page and it automatically update the `og:description` like it does in `nuxt.config.js`. Thanks.
