### ISSUE TITLE
Why this lib such awesome ?

### ISSUE THREAD

**Issue by Shuunen** [nuxt-community/pwa-module#53]
Sorry but I had to leave some :heart: to contributors here,

This module is working great, my web app PWA audit goes from 12% to 82% after just installing and following the [setup guide](https://pwa.nuxtjs.org/setup.html) 

![image](https://user-images.githubusercontent.com/439158/37764181-46fbb5f2-2dc1-11e8-9a3f-0a19df4ca5dd.png)

Thanks all & great job :+1: 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c34">#c34</a>)</em></sub></div>

**Comment by manniL** [comment]
It should even be pushed to 100 :thinking: 
What is missing?

**Comment by manniL** [comment]
HTTPS redirection is something you need to do yourself.

About fallback content: This is easily possible through meta-data in the nuxt config. You need to add `noscript` content. I did it [like this](https://github.com/Developmint/developmint.de/blob/76ca95e974674d7fccb8fba14f32632da80664ea/nuxt.config.js#L52)

**Comment by Shuunen** [comment]
> About fallback content: This is easily possible through meta-data in the nuxt config. You need to add noscript content. I did it like this

Totally worked :tada:  thanks @manniL ! 

I'm using netlify.com with free open source plan, but they dont do http->https redirection without paid domain apparently

Also I tried to do this in JS, it works with `document.location.protocol = 'https'` but does not fool Google Audits :yum: 

![image](https://user-images.githubusercontent.com/439158/37831913-512f7130-2ea7-11e8-8f53-02f137499b96.png)

**Comment by manniL** [comment]
You are welcome :relaxed: 

Ah, alright! I use my own VPS for hosting, so it's easy to configure NGINX or Apache to do it. But apparently you can force ssl on netlify even without custom domains (see [Redirects](https://www.netlify.com/docs/redirects/)). :thinking:

**Comment by Shuunen** [comment]
I owe you this :100: 

![image](https://user-images.githubusercontent.com/439158/37832945-5c6cc194-2eaa-11e8-98ae-7a22594c4605.png)

Thanks @manniL , really :+1:

**Comment by manniL** [comment]
No problem @Shuunen :relaxed: Glad I was able to help!

**Comment by pi0** [comment]
Thanks, @Shuunen for your kind words and @manniL for nice help. Closing as it seems fixed.
