### ISSUE TITLE
Enable offline GA through workbox

### ISSUE THREAD

**Issue by manniL** [nuxt-community/pwa-module#54]
Hey,

I've learned today that GA can be enabled to track offline user actions as well [with workbox](https://developers.google.com/web/tools/workbox/guides/enable-offline-analytics). It'd be great if this could be integrated (and auto-enabled when the nuxt analytics module [or GA] is present)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c29">#c29</a>)</em></sub></div>

**Comment by pi0** [comment]
Will be available in `3.0.0-beta.2+`. All credits to @manniL :heart:
