### ISSUE TITLE
README improvement request around Workbox

### ISSUE THREAD

**Issue by BruceHem** [nuxt-community/pwa-module#6]
First of all I must say this module is freaking awesome, makes starting PWA easier, but I'd like to see improvement to the README around workbox section, any example with this?

**Comment by pi0** [comment]
@BruceHem There are new docs and options for workbox module. Is there any special thing missing in docs?

**Comment by BruceHem** [comment]
@pi0 I just checked the new docs, it’s way better. Thank you.
