### ISSUE TITLE
Icons are not found

### ISSUE THREAD

**Issue by pawel-miczka** [nuxt-community/pwa-module#61]
Hi,

I have problem with this module. I added icon.png to /static folder and after I ran "yarn build" it shows that icons are created but then in Chrome Console in Application tab (im Manifest section) I have 7 blank icons (64x64, 120x120 etc.).

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c36">#c36</a>)</em></sub></div>

**Comment by pawel-miczka** [comment]
.. why this is closed :O ? 
Anyway: icons are working on dev, but on production they are not.

**Comment by pierreberchtold** [comment]
Would it be possible to rename the 'icons' directory? It looks like some hosting providers do not accept this directory name: https://ch.godaddy.com/help/warum-werden-dateien-in-meinem-symbole-verzeichnis-nicht-angezeigt-261?lang=en

**Comment by manniL** [comment]
@pierreberchtold Could you create a new feature request for that? ☺️
