### ISSUE TITLE
Service Worker not registered

### ISSUE THREAD

**Issue by cloudbluedigital** [nuxt-community/pwa-module#62]
Hi!

I have started using this package and I set it up like this:
```
  modules: [
      '@nuxtjs/dotenv',
      '@nuxtjs/axios',
      '@nuxtjs/toast',
      '@nuxtjs/pwa',
    ['nuxt-validate', {
      lang: 'en',
    }]
  ],

  workbox: {
    runtimeCaching: [
      {
        // Should be a regex string. Compiles into new RegExp('https://my-cdn.com/.*')
        urlPattern: 'https://cdn.timeandattendance/.*',
        // Defaults to `networkFirst` if omitted
        handler: 'cacheFirst',
        // Defaults to `GET` if omitted
        method: 'GET'
        }
      ]
  },
```
However when I use google chrome audits test it says that

It does not register Service worker and that it does not respond with 200 when offline, and as far as I am aware, this is what this package is supposed to do?

**Comment by Extarys** [comment]
Can we please close this as it is a duplicate? Thanks :robot:

**Comment by cloudbluedigital** [comment]
what you mean it is a duplicate, haven't seen this question somewhere else
