### ISSUE TITLE
Workbox and HTML5 video on iOS Safari

### ISSUE THREAD

**Issue by mixn** [nuxt-community/pwa-module#64]
### Version

[2.0.8](https://github.com/nuxt-community/pwa-module/releases/tag/2.0.8)

### Reproduction link

[https://264-education-heitbuiyfy.now.sh/](https://264-education-heitbuiyfy.now.sh/)

### Steps to reproduce

Visit the reproduction link in any browser / OS combination and the video plays without problems. Do so on Mobile Safari on iOS and the video freezes after 1–3s and / or doesn’t load at all.

This only happens when the pwa-module (the workbox part of it) is used. The video then plays only the very first time and often freezes after 1–3s, often it doesn’t load / play at all.

This issue looks *very* similar to this https://github.com/angular/angular/issues/23447 Angular issue, so it might be a core problem inside iOS / their SW implementation? I am not sure, I just ran into this.

I have tried explicitly ignoring the file with `globIgnores` and/or `exclude`, but wasn’t successful.

Thank you in advance, I appreciate it and the work you have put into this. :)

### What is expected ?

Video should play when SW is activated in any browser / on any OS.

### What is actually happening?

Video freezes after 1–3s and / or doesn’t play on Mobile Safari on iOS when SW is activated.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c42">#c42</a>)</em></sub></div>

**Comment by tetreault** [comment]
Can confirm this happens

**Comment by CarterLi** [comment]
I was trying resolving this issue by add workbox range-request plugin:

```js
// plugins/workbox-range-request.js

workbox.routing.registerRoute(
  /.*\.(mp4|webm)/,
  workbox.strategies.cacheFirst({
    plugins: [
      new workbox.rangeRequests.Plugin(),
    ],
  }),
);
```

```js
// nuxt.config.js
{ workbox: { routingExtensions: '@/plugins/workbox-range-request.js' } }
```

Please see if it helps

**Comment by mixn** [comment]
@CarterLi Has that resolved the issue for you? The Angular thread I linked above also mentions the range-request plugin.

**Comment by CarterLi** [comment]
@mixn Yes. SW can correctly returns 206 when using range-request plugin.

**Comment by pi0** [comment]
Thanks, @CarterLi. Added the to doc.s

**Comment by rwwagner90** [comment]
I'm unsure if this is the issue I am hitting, but videos will not ever load on Safari. It tries to grab them from the service worker and fails every time. Any ideas?

**Comment by mirkopoloni** [comment]
> I'm unsure if this is the issue I am hitting, but videos will not ever load on Safari. It tries to grab them from the service worker and fails every time. Any ideas?

Hi @rwwagner90,
I had the same problem and the solution of this issue fixed it for me.
Do you still have the problem?

**Comment by rwwagner90** [comment]
@mirkopoloni I am trying the fix now. I did not see that there was a recommended fix. If this is necessary to have video files, why is it not included by default?

**Comment by mirkopoloni** [comment]
@rwwagner90 I didn't investigate why the solution isn't included by default and I can't answer this question.
Maybe someone else can tell us more about this.
Hope it solved your problem.

**Comment by CarterLi** [comment]
It seems that APIs are changed in workbox 5.x. Scripts updated:

```js
/* eslint-disable no-undef */
workbox.routing.registerRoute(
  /.*\.(mp4|webm)/,
  new workbox.strategies.CacheFirst({
    cacheName: 'videos',
    plugins: [
      new workbox.rangeRequests.RangeRequestsPlugin(),
    ],
  }),
  'GET'
);
```

**Comment by rwwagner90** [comment]
@CarterLi do we need to support both, based on what Safari version a user might have?

**Comment by CarterLi** [comment]
> @CarterLi do we need to support both, based on what Safari version a user might have?

What did you mean with `based on what Safari version a user might have`

**Comment by rwwagner90** [comment]
@CarterLi I mean based on the Safari version the user has, wouldn't the API be different? This new version works in new Safari I assume?
