### ISSUE TITLE
WorkboxError on fresh install

### ISSUE THREAD

**Issue by ghost** [nuxt-community/pwa-module#66]
### Version

[v0.4.0](https://github.com/nuxt-community/pwa-module/releases/tag/v0.4.0)

### Reproduction link

[https://github.com/nuxt-community/pwa-template](https://github.com/nuxt-community/pwa-template)

### Steps to reproduce

1. Install:
```
$ vue init nuxt-community/pwa-template my-project  
$ cd my-project                     
# install dependencies
$ npm install # Or yarn install
$ npm run build
$ npm start
```
2. Navigate to localhost:3000

### What is expected ?

Error-less PWA application.

### What is actually happening?

Error in browser console when entering /:
```
workbox.3de3418b.js:158 Uncaught (in promise) WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"http://localhost:3000/_nuxt/layouts_default.061f990e7d3f96dc329e.js","error":{}}'
    at http://localhost:3000/_nuxt/workbox.3de3418b.js:160:1358
    at Generator.throw (<anonymous>)
    at step (http://localhost:3000/_nuxt/workbox.3de3418b.js:83:30)
    at http://localhost:3000/_nuxt/workbox.3de3418b.js:96:13
WorkboxError @ workbox.3de3418b.js:158
(anonymous) @ workbox.3de3418b.js:160
step @ workbox.3de3418b.js:83
(anonymous) @ workbox.3de3418b.js:96
```

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c46">#c46</a>)</em></sub></div>

**Comment by maiconpazin** [comment]
I am having the same problem. An error occur when the workbox try to cache the manifest file because the request is returning 404. I think that it occur because I have 3 containers for my application and the load balancer choice one of them to receive the request and maybe there is a delay between the containers to get ready with the last code version after a deploy.

There is a way to catch the workbox error and avoid to broke all the page?

**Comment by pi0** [comment]
Service worker file has a default error handler which should prevent any application errors in case of `sw.js` 404.

https://github.com/nuxt-community/pwa-module/blob/dev/packages/workbox/templates/sw.register.js#L7

Anyway please try the latest release  (3.0.0 would be perfect) and comment if any problem still exists with latest chrome.
