### ISSUE TITLE
Web app banners

### ISSUE THREAD

**Issue by memic84** [nuxt-community/pwa-module#69]
### What problem does this feature solve?

Support for iOS 11.3, where web app banners are not shown and partial PWA support. I think that we need some support for those browsers which don't support everything yet.

### What does the proposed changes look like?

Detect if when the browser is on iOS, and show a install prompt for the PWA the second the the user visits.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c48">#c48</a>)</em></sub></div>

**Comment by tetreault** [comment]
I think this issue is bigger than Nuxt, and actually related to iOS itself. We recently faced this issue in a client PWA outside of Nuxt.

**Comment by memic84** [comment]
I think so, this is the current lacking support from Apple. Close issue?

**Comment by tetreault** [comment]
I also recently found out that Apple didn't even implement WebRTC into PWA's (or anything that's a webview). It only works in Safari. Wish Apple wasn't so half-assed.

**Comment by pi0** [comment]
Added appreciate label :)
