### ISSUE TITLE
e.$OneSignal.on is not a function

### ISSUE THREAD

**Issue by voxivoid** [nuxt-community/pwa-module#76]
I'm working on a project that uses @nuxtjs/pwa along with @nuxtjs/onesignal and I am having an issue while setting up a listener to the `subscriptionChange` event on mounted inside of my default layout component. Sometimes it throws `e.$OneSignal.on is not a function` and I can't get why. On the setup, I've added the onesignal module before the pwa as the documentation says. This is what I'm doing in my component:

```
mounted() {
    this.$OneSignal.push(() => {
      this.$OneSignal.on('subscriptionChange', isSubscribed => {
        if (isSubscribed) {
          this.$OneSignal.getUserId().then(deviceId => this.addDeviceId(deviceId));
        }
      });
    });
},
```

I've tried to log the `this.$OneSignal` and when I get the error it prints an array with all the functions that were pushed into `this.$OneSignal` instead of the OneSignal object with all the methods, which is weird because this code should never be called before the load of the script. Any help would be appreciated! 

Thanks!

**Comment by voxivoid** [comment]
I know how arrow functions work, the this.$OneSignal.on that is being called is the one from the component scope. Beside this, I'm also following the module [docs](https://pwa.nuxtjs.org/modules/onesignal.html) and they use arrow functions. I tried what you said but it says the this is undefined on the inside function.

**Comment by juniorgarcia** [comment]
Try to isolate the `this` into a variable, then use that variable inside your closures:

```
mounted() {
  let self = this;
  this.$OneSignal.push(() => {
    self.$OneSignal.on('subscriptionChange', (isSubscribed) => {
      if (isSubscribed) {
        self.$OneSignal.getUserId().then((deviceId) => { self.addDeviceId(deviceId) });
      }
    });
  });
},
```

**Comment by lovishagg** [comment]
@voxivoid Did you manage to fix this? I've the same issue when in production build. Everything works fine on my dev mode. Please note that I am using this inside a component and the mode of my nuxt application is SSR also am not using any docker services. Please let me know, it'll be a great help.
`<template>
	<div v-if="supportedBrowser">
		<div id="my-notification-button" v-if="!isSubscribed" @click="subscribe">Subscribe to Notifications</div>
		<div id="my-notification-button" v-else @click="unsubscribe">Un-Subscribe from Notifications</div>
	</div>
</template>
<style scoped>
#my-notification-button{
	position: fixed;
	bottom: 0;
	left: 0;
	padding: 10px;
	width: 100%;
	text-align: center;
	background-color: white;
	text-decoration: none;
	color: black;
	cursor: pointer;
}
</style>
<script>
export default {
	data(){
		return {
			supportedBrowser: false,
			isSubscribed: false,
			currentDevice: null
		}
	},
	mounted(){
		this.isSubscribed = this.$auth.loggedIn ? this.$auth.user.notify : false;
		var OneSignal = window.$OneSignal;
		OneSignal.push(() => {
			OneSignal.on('subscriptionChange', this.update);
		});
		this.update();	
	},
	methods: {
		update(){
			this.$OneSignal.push(async () => {
				var isPushSupported = await this.$OneSignal.isPushNotificationsSupported();
				this.supportedBrowser= isPushSupported;
				if (isPushSupported) {
					var isEnabled = await this.$OneSignal.isPushNotificationsEnabled();
					var deviceId = await this.$OneSignal.getUserId();
					this.isSubscribed = isEnabled;
					this.currentDevice = deviceId;
					var reqBody = {
						isSubscribed: this.isSubscribed,
						currentDevice: this.currentDevice
					}
					if (isEnabled) {
						var response = await this.$axios.post("/users/subscribe", reqBody);
					} else {
						console.log("Notifications are not enabled");
						var response = await this.$axios.post("/users/unsubscribe", reqBody);
					}
				} else {
					console.log("Does not support notifications");
				}
			});
		},
		subscribe(){
			console.log("here");
			this.$OneSignal.push(async () => {
				console.log("here1");	
				var isSubscribed = await this.$OneSignal.setSubscription(true);
			});
		},
		unsubscribe(){
			console.log("here2");
			this.$OneSignal.push(async () => {
				console.log("here3");
				var isSubscribed = await this.$OneSignal.setSubscription(false);
			});
		}
	}
}
</script>`

**Comment by chhumsina** [comment]
> @voxivoid Did you manage to fix this? I've the same issue when in production build. Everything works fine on my dev mode. Please note that I am using this inside a component and the mode of my nuxt application is SSR also am not using any docker services. Please let me know, it'll be a great help.
> `
> 
> <div id="my-notification-button" v-if="!isSubscribed" @click="subscribe">Subscribe to Notifications
> 
> <div id="my-notification-button" v-else @click="unsubscribe">Un-Subscribe from Notifications
> 
> <style scoped> #my-notification-button{ position: fixed; bottom: 0; left: 0; padding: 10px; width: 100%; text-align: center; background-color: white; text-decoration: none; color: black; cursor: pointer; } </style> <script> export default { data(){ return { supportedBrowser: false, isSubscribed: false, currentDevice: null } }, mounted(){ this.isSubscribed = this.$auth.loggedIn ? this.$auth.user.notify : false; var OneSignal = window.$OneSignal; OneSignal.push(() => { OneSignal.on('subscriptionChange', this.update); }); this.update(); }, methods: { update(){ this.$OneSignal.push(async () => { var isPushSupported = await this.$OneSignal.isPushNotificationsSupported(); this.supportedBrowser= isPushSupported; if (isPushSupported) { var isEnabled = await this.$OneSignal.isPushNotificationsEnabled(); var deviceId = await this.$OneSignal.getUserId(); this.isSubscribed = isEnabled; this.currentDevice = deviceId; var reqBody = { isSubscribed: this.isSubscribed, currentDevice: this.currentDevice } if (isEnabled) { var response = await this.$axios.post("/users/subscribe", reqBody); } else { console.log("Notifications are not enabled"); var response = await this.$axios.post("/users/unsubscribe", reqBody); } } else { console.log("Does not support notifications"); } }); }, subscribe(){ console.log("here"); this.$OneSignal.push(async () => { console.log("here1"); var isSubscribed = await this.$OneSignal.setSubscription(true); }); }, unsubscribe(){ console.log("here2"); this.$OneSignal.push(async () => { console.log("here3"); var isSubscribed = await this.$OneSignal.setSubscription(false); }); } } } </script>`

Me also. Local working well but production error
![Capture](https://user-images.githubusercontent.com/3894767/79246098-37d9a180-7ea3-11ea-940e-4f360008c408.PNG)
