### ISSUE TITLE
The workbox is caching my landing page

### ISSUE THREAD

**Issue by koresar** [nuxt-community/pwa-module#79]
### Version

[2](https://github.com/pwa-module/releases/tag/2)

### Reproduction link

[https://example.com/NOT_APPLICABLE](https://example.com/NOT_APPLICABLE)

### Steps to reproduce

Just add `@nuxt/pwa` to your nuxt app

### What is expected ?

The `/` page is not offline cached, or at least uses "netowrkFirst" strategy.

### What is actually happening?

My landing page is somewhat dynamic. It must not be cached for offline use.

I couldn't find a way to override the default caching strategy (which is "offlineFirst") for my landing page and any other non-nuxt assets.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c58">#c58</a>)</em></sub></div>

**Comment by benoitemile** [comment]
what do you want to achieve ?

**Comment by galvez** [comment]
@koresar That's unlikely, `/.*` uses the `networkFirst` caching strategy.

Check out the generated `static/sw.js` file.

**Comment by harish0507** [comment]
Try adding a runtimeCache for the landing page ```/```
```
runtimeCaching: [{ urlPattern: '/' }]
```

**Comment by pi0** [comment]
Please try `3.0.0-beta.0` with `offline: false` option to disable this behavior. BTW as it is now correctly using `networkFirst` strategy it should be safe to be enabled.
