### ISSUE TITLE
Netlify Deployment fails with jimp Version 0.3.5

### ISSUE THREAD

**Issue by joberthel** [nuxt-community/pwa-module#84]
https://github.com/nuxt-community/pwa-module/blob/ef670b81836e45aa3e732e6e5027b71eb90eee92/packages/icon/package.json#L13

It fails with the error: "Cannot find module 'jpgjs'"
I guess this will happen on every AWS environment.

If i add the following to my package.json, everything works fine:
"jimp": "0.3.4"

Related: https://github.com/oliver-moran/jimp/issues/560

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c61">#c61</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks for this bug report. While waiting for @hipstersmoothie's new release i''ll fallback jimp version

**Comment by hipstersmoothie** [comment]
You can make a custom build of jimp using 

https://github.com/oliver-moran/jimp/tree/master/packages/custom 

and exclude the TIFF package. Or you can wait until the new version of UTIF is released. 

https://github.com/photopea/UTIF.js/issues/43

**Comment by chrysanthos** [comment]
FWIW, I am having the same error on Heroku.

**Comment by simllll** [comment]
I experienced this issue now even with the latest release? Seems we need to get UTIF released quickly to get this covered.

**Comment by hipstersmoothie** [comment]
No release has covered this yet on jimp's end. You could always make a custom build of jimp that doesn't use the tiff type https://github.com/oliver-moran/jimp/tree/master/packages/custom

**Comment by husayt** [comment]
The issue here is not with jimp, but with this module using a library which
is not yet ready for use.

**Comment by hipstersmoothie** [comment]
I totally agree. Regardless though it's breaking your build. To sidestep this right now you could just configure a custom Jimp and get all your builds passing. But it's only a band-aid if you really need TIFF support.

**Comment by pi0** [comment]
Fixed with >= 0.4.0: https://github.com/oliver-moran/jimp/issues/560#issuecomment-417966353
