### ISSUE TITLE
Hot Reload make page not load anything till restart of server

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/pwa-module#88]
### Version

[v2.4.0](https://github.com/pwa-module/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

In chrome after some hot reloads page stop loading at all and only anonymous window work.
Terrible developing experience.

### What is expected ?

No stuck page behaviour

### What is actually happening?

stuck page behaviour

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c63">#c63</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: https://github.com/nuxt-community/pwa-module/pull/60#issuecomment-407008485, https://github.com/nuxt/nuxt.js/issues/3828,

**Comment by manniL** [comment]
Maybe disable caching of `/_nuxt/HASH_HERE.hot-update.json` could fix the problem :thinking:

**Comment by manniL** [comment]
A temporary workaround: 

* Firefox: Use `Forget this page`
* Chrome: Reset the service worker


How the problem can be reproduced:

* `npm run build && npm run start`
* Open the page
* `npm run dev` (Don't close the page where your project is running, URL's must be equal in dev and prod mode)
* Click around the page to trigger loading while the service worker is still active and not cleared
* Edit sth. in your editor to trigger HMR
* See flickering

### Sophisticated workarounds?

* Don't cache `hot reload` files. 
**Problem:** Doesn't fully resolve the problem. In the worst case scenario, you are loading the full *dev version* (including non-hashed nuxt files that'll be cached)

* Don't cache **all dev nuxt files**. 
**Problem:** We'd need a list and a decent check (that might influence live performance)

**Comment by pi0** [comment]
This problem should be finally fixed with `3.0.0-beta.1`.

1. A regex extension added to ignore webpack HMR from workbox (tests: https://github.com/nuxt-community/pwa-module/blob/dev/test/hmr.js).

2. added `[sw.dev.js]` that fast claims all tabs and disables most of workbox.

**Comment by manniL** [comment]
@pi0 Hero <3
