### ISSUE TITLE
PWA cause live site to stuck on loading files/api calls

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/pwa-module#89]
### Version

[v2.4.0](https://github.com/pwa-module/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

Here some example screenshot https://i.imgur.com/hQe6ppA.png ( 5h for request xD ) https://i.imgur.com/575szHF.png https://i.imgur.com/OkF2uo9.png
File loading just stuck until that page manually opened in new tab. As soon as it opened - query finished. As long as it dont open - query in pending state and running.
Another fix is to open developer tools in chrome go to application and push sync button - then request will finish too. https://i.imgur.com/OCjjv3E.png
Same happens in FF.
Maybe somewhere race condition happens

### What is expected ?

queries from service worker get stuck

### What is actually happening?

queries finished without stucking

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c65">#c65</a>)</em></sub></div>

**Comment by aldarund** [comment]
Reliable way to reproduce it for me
open site -> switch to other tabs browse something etc for few minutes -> switch back and click any link

**Comment by aldarund** [comment]
Also sometime i see in console when this happens -> Service Worker termination by a timeout timer was canceled because DevTools is attached.
But certainly not always, maybe like once in 10 time, so maybe not relevant

**Comment by aldarund** [comment]
This might be happening only with dev tools opened, yet to reproduce with dev tools closed

**Comment by pi0** [comment]
caching problems with dev tool has been resolved for (3.0.0). Other issues are probably directly related to workbox itself.
