### ISSUE TITLE
Extending workbox

### ISSUE THREAD

**Issue by chabib** [nuxt-community/pwa-module#9]
How to extend workbox in this module, so I can use other service worker features such as background sync and push notification?

**Comment by derekshull** [comment]
Same question here.

**Comment by Darkside73** [comment]
Also looking for get this works with web push implementations like Google FCM

**Comment by pi0** [comment]
Please see new docs. It is now possible adding more service workers using **importScripts**

**Comment by chabib** [comment]
@pi0 I know that by adding additional script to sw achieve the goal to use other sw features.
But is there a way to achieve it by writing workbox script instead? Even if it is a workaround outside this module.
