### ISSUE TITLE
Basic Auth won't prompt for credentials due to service worker caching response

### ISSUE THREAD

**Issue by XanderLuciano** [nuxt-community/pwa-module#94]
### Affects: v2.4.0

Currently with a service worker caching pages, HTTP Basic Auth is broken. Upon initial load a user will be prompted for credentials, however, due to caching, this prompt will never be shown a second time unless the user clears their cache.

Originally filed as a chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=623464  
Though this appears to be an intentional "feature" to prevent random credential requests.

I am not sure what the proper solution to this is, though a possible workaround is outlined here: https://thatemil.com/blog/2018/02/21/pwa-basic-auth/

Additional workbox support is needed at this point before addressing this issue.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c72">#c72</a>)</em></sub></div>

**Comment by XanderLuciano** [comment]
@manniL Please reopen and change to bug / feature request.

**Comment by henrixapp** [comment]
This is undocumented fixed in https://github.com/nuxt-community/pwa-module/blob/11795599edccb1b9beae892c71a6f8db0d76da9c/packages/manifest/index.js#L75 , just provide `crossorigin: 'use-credentials'` in your manifest section of nuxt.config.js

**Comment by pi0** [comment]
Added to the docs for next version.

**Comment by fernhub** [comment]
> Added to the docs for next version.

@pi0 what docs do you mean? because in the official site https://pwa.nuxtjs.org/modules/manifest.html, I couldn't find anything related to this issue, and I really think a lot of people could benefit from having it there and avoiding having to google the problem and end up in this thread.

**Comment by DispatchCommit** [comment]
@fernhub It's right here: https://pwa.nuxtjs.org/modules/workbox.html#basic-auth

**Comment by XanderLuciano** [comment]
@fernhub It's right here: https://pwa.nuxtjs.org/modules/workbox.html#basic-auth

**Comment by FelixRe0** [comment]
Even with the proposed fix I am experiencing the issue. Crossorigin is set correctly in index.html.
`<link data-n-head="1" rel="manifest" href="/_nuxt/manifest.c09e73a7.json" crossorigin="use-credentials">`

Changing the workbox configuration to set credentials to same-origin did not resolve the problem either. 

```
workbox.routing.registerRoute(new RegExp('/_nuxt/'), new workbox.strategies.CacheFirst ({"credentials":"same-origin"}), 'GET')
workbox.routing.registerRoute(new RegExp('/'), new workbox.strategies.NetworkFirst ({"credentials":"same-origin"}), 'GET')
```

Am I missing anything?
